/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import FloatLib.Floats.Formats.IEEE754.Native
public import FloatLib.Floats.Formats.BinaryInterchange.Configured.Rounding.Runtime
public import FloatLib.Floats.Formats.BinaryInterchange.DirectedSemantics.Rational.Conversion

/-!
# Arithmetic for nested quotient rules

Checked operations retain range-loss information until the complete quotient has been evaluated.
The cold path evaluates the original finite coefficient trees over `Rat`, then rounds each
coefficient through FloatLib to the requested format. This is scoped to one quotient: it cannot
recover information lost before its inputs were formed.
-/

@[expose] public section

namespace TorchLean.Numeric

/-- Coefficients in the algebra generated by `n` commuting square-zero variables. -/
inductive QuotientCoefficients : Nat → Type where
  | scalar : Rat → QuotientCoefficients 0
  | dual {n : Nat} :
      QuotientCoefficients n → QuotientCoefficients n → QuotientCoefficients (n + 1)

namespace QuotientCoefficients

/-- Constant coefficient, obtained by setting all square-zero variables to zero. -/
def primal : {n : Nat} → QuotientCoefficients n → Rat
  | _, .scalar x => x
  | _, .dual x _ => primal x

/-- Add corresponding rational coefficients without rounding. -/
def add : {n : Nat} → QuotientCoefficients n → QuotientCoefficients n →
    QuotientCoefficients n
  | _, .scalar x, .scalar y => .scalar (x + y)
  | _, .dual x dx, .dual y dy => .dual (add x y) (add dx dy)

/-- Subtract corresponding rational coefficients without rounding. -/
def sub : {n : Nat} → QuotientCoefficients n → QuotientCoefficients n →
    QuotientCoefficients n
  | _, .scalar x, .scalar y => .scalar (x - y)
  | _, .dual x dx, .dual y dy => .dual (sub x y) (sub dx dy)

/-- Multiply coefficient trees using the product rule at each square-zero extension. -/
def mul : {n : Nat} → QuotientCoefficients n → QuotientCoefficients n →
    QuotientCoefficients n
  | _, .scalar x, .scalar y => .scalar (x * y)
  | _, .dual x dx, .dual y dy => .dual (mul x y) (add (mul dx y) (mul x dy))

/-- The caller checks that the denominator's primal is nonzero before entering this recursion. -/
def div : {n : Nat} → QuotientCoefficients n → QuotientCoefficients n →
    QuotientCoefficients n
  | _, .scalar x, .scalar y => .scalar (x / y)
  | _, .dual x dx, .dual y dy =>
      let q := div x y
      .dual q (div (sub dx (mul q dy)) y)

end QuotientCoefficients

/--
Operations used inside one complete quotient, together with finite coefficient conversion.

Internal byte flags record nonfinite or subnormal results, including a nonzero product or quotient
rounded to zero. Zero means no range loss; recursive carriers combine flags with bitwise OR.
The checked-operation entrypoints expose the same Boolean result without converting at each
internal node. Unsupported carriers use the ordinary operations and do not supply a conversion.
-/
class QuotientArithmetic (α : Type) where
  supported : Bool := false
  depth : Nat := 0
  addWithFlags : α → α → α × UInt8
  subWithFlags : α → α → α × UInt8
  mulWithFlags : α → α → α × UInt8
  divWithFlags : α → α → α × UInt8
  encode : α → Option (QuotientCoefficients depth) := fun _ => none
  decode : QuotientCoefficients depth → Option α := fun _ => none
  /-- Copy the scalar primal's native sign of zero after replaying derivative coefficients. -/
  copyPrimal : α → α → α := fun _ y => y

instance (priority := low) {α : Type} [Add α] [Sub α] [Mul α] [Div α] :
    QuotientArithmetic α where
  addWithFlags x y := (x + y, 0)
  subWithFlags x y := (x - y, 0)
  mulWithFlags x y := (x * y, 0)
  divWithFlags x y := (x / y, 0)

namespace QuotientArithmetic

@[inline] def divChecked {α : Type} [ops : QuotientArithmetic α] (x y : α) : α × Bool :=
  let (value, flags) := ops.divWithFlags x y
  (value, 0 < flags)

/--
Replay only finite input trees with an invertible denominator.

Only coefficient conversion crosses this cold boundary, leaving the checked arithmetic
operations available for specialization in the caller.
-/
@[noinline] def replay? {α : Type} {depth : Nat}
    (encode : α → Option (QuotientCoefficients depth))
    (decode : QuotientCoefficients depth → Option α) (x y : α) : Option α := do
  let a ← encode x
  let b ← encode y
  if b.primal == 0 then none else decode (QuotientCoefficients.div a b)

/-- Native constants and rational rounding, selected by the scalar type. -/
class NativeFormat (α : Type) where
  zero : α
  minNormal : α
  negMinNormal : α
  /-- Round a rational once to the native scalar type. -/
  round : Rat → α

-- Initialize the native constants once, outside all checked operations.
@[noinline] instance : NativeFormat Float where
  zero := Float.ofBits 0
  minNormal := Float.ofBits 0x0010000000000000
  negMinNormal := Float.ofBits 0x8010000000000000
  round value := FloatLib.Floats.ExecFloat.Binary.toFloat <|
    FloatLib.Floats.ExecFloat.Binary.ofModel <|
      FloatLib.Floats.Formats.BinaryInterchange.Model.roundRatQ
        FloatLib.Floats.Formats.BinaryInterchange.FloatFormat.binary64 value

@[noinline] instance : NativeFormat Float32 where
  zero := Float32.ofBits 0
  minNormal := Float32.ofBits 0x00800000
  negMinNormal := Float32.ofBits 0x80800000
  round value := FloatLib.Floats.ExecFloat.Binary.toFloat32 <|
    FloatLib.Floats.ExecFloat.Binary.ofModel <|
      FloatLib.Floats.Formats.BinaryInterchange.Model.roundRatQ
        FloatLib.Floats.Formats.BinaryInterchange.FloatFormat.binary32 value

export NativeFormat (round)

namespace Native

variable {α : Type} [NativeFormat α] [BEq α] [LT α] [DecidableLT α] [Sub α]

@[inline] def zeroFlag (x : α) : UInt8 := (x == NativeFormat.zero).toUInt8

-- A finite self-difference is zero; a nonfinite self-difference is NaN.
-- Reflexive equality of that difference detects NaN without a floating zero constant.
@[inline] def nonfiniteFlag (x : α) : UInt8 :=
  let difference := x - x
  (difference == difference).toUInt8 ^^^ 1

-- Excluding zero from the interval (-minNormal, minNormal) leaves the subnormals.
@[inline] def rangeFlags (zero : α → UInt8) (x : α) : UInt8 :=
  if ((decide (NativeFormat.negMinNormal < x)).toUInt8 &&&
      (decide (x < NativeFormat.minNormal)).toUInt8) == 1 then
    zero x ^^^ 1
  else nonfiniteFlag x

/-- Whether a native result is nonfinite or subnormal; its type selects the format. -/
@[inline] def rangeLoss (x : α) : Bool := 0 < rangeFlags zeroFlag x

-- Only predicates cross this boundary. Value-producing arithmetic remains inline.
-- The open interval contains only finite values. Its branch needs zero checks;
-- outside it, only nonfiniteness can raise a flag.
@[noinline, specialize] def addSubFlags (zero : α → UInt8) (z : α) : UInt8 :=
  rangeFlags zero z

/-- Range flags for the actual native product `z = x * y`, using native zero equality.
The open subnormal interval includes zero; nonzero inputs detect a product rounded to zero.
This formula requires the actual product, not an independently supplied third value. -/
@[noinline, specialize] def productFlags (zero : α → UInt8) (x y z : α) : UInt8 :=
  if ((decide (NativeFormat.negMinNormal < z)).toUInt8 &&&
      (decide (z < NativeFormat.minNormal)).toUInt8) == 1 then
    (zero x ^^^ 1) &&& (zero y ^^^ 1)
  else nonfiniteFlag z

/-- Range flags for the actual native quotient `z = x / y`, using native zero equality.
A zero denominator already makes the result nonfinite. A zero or subnormal result with a
nonzero numerator requires replay. This formula assumes `z` is the actual division result. -/
@[noinline, specialize] def quotientFlags (zero : α → UInt8) (x z : α) : UInt8 :=
  if ((decide (NativeFormat.negMinNormal < z)).toUInt8 &&&
      (decide (z < NativeFormat.minNormal)).toUInt8) == 1 then
    zero x ^^^ 1
  else nonfiniteFlag z

@[inline] def addWithFlags [Add α] (x y : α) : α × UInt8 :=
  let z := x + y
  (z, addSubFlags zeroFlag z)

@[inline] def subWithFlags (x y : α) : α × UInt8 :=
  let z := x - y
  (z, addSubFlags zeroFlag z)

@[inline] def mulWithFlags [Mul α] (x y : α) : α × UInt8 :=
  let z := x * y
  (z, productFlags zeroFlag x y z)

@[inline] def divWithFlags [Div α] (x y : α) : α × UInt8 :=
  let z := x / y
  (z, quotientFlags zeroFlag x z)

end Native

@[inline] instance : QuotientArithmetic Float where
  supported := true
  addWithFlags x y := Native.addWithFlags x y
  subWithFlags x y := Native.subWithFlags x y
  mulWithFlags x y := Native.mulWithFlags x y
  divWithFlags x y := Native.divWithFlags x y
  encode x := (FloatLib.Floats.ExecFloat.Binary.toRat?
    (FloatLib.Floats.ExecFloat.Binary.ofFloat x)).map QuotientCoefficients.scalar
  decode | .scalar x => some (round x)
  copyPrimal x _ := x

@[inline] instance : QuotientArithmetic Float32 where
  supported := true
  addWithFlags x y := Native.addWithFlags x y
  subWithFlags x y := Native.subWithFlags x y
  mulWithFlags x y := Native.mulWithFlags x y
  divWithFlags x y := Native.divWithFlags x y
  encode x := (FloatLib.Floats.ExecFloat.Binary.toRat?
    (FloatLib.Floats.ExecFloat.Binary.ofFloat x.toFloat)).map QuotientCoefficients.scalar
  decode | .scalar x => some (round x)
  copyPrimal x _ := x

section Configured

open FloatLib.Floats.Formats.BinaryInterchange
open FloatLib.Floats (ExecFloat)

variable {format : FloatFormat} {plan : Configured.StoragePlan format} {code : Type}
    [ExecFloat.ModelCodec plan (Model format) code]

local notation "Value" => ExecFloat (Configured.Family format code plan)

/--
FloatLib exception status plus the stricter range predicate needed by a nested quotient.

IEEE underflow requires inexactness. An exact subnormal intermediate must also trigger replay,
since subsequent multiplication or division can lose coefficients. Ordinary inexact rounding
alone does not trigger replay.
-/
def configuredFlags (outcome : Value × Model.IEEEStatus) : UInt8 :=
  let (value, status) := outcome
  (status.invalid || status.divideByZero || status.overflow || status.underflow ||
    !ExecFloat.Binary.isFinite value || ExecFloat.Binary.isSubnormal value).toUInt8

/--
Configured IEEE values use FloatLib's nearest-even operations and exact finite decoder.

The complete derivative tree is replayed by the recursive `Dual` instance. Every coefficient is
rounded independently to the original descriptor and storage plan, including formats wider than
binary64. Finite-only encodings are not enabled: their saturation policy would require a separate
derivative contract. True coefficients outside the IEEE range may still round to zero or infinity.
-/
instance configured : QuotientArithmetic Value where
  supported := format.isIEEE
  addWithFlags x y :=
    let outcome := ExecFloat.Binary.addWithStatus x y .nearestEven
    (outcome.1, configuredFlags outcome)
  subWithFlags x y :=
    let outcome := ExecFloat.Binary.subWithStatus x y .nearestEven
    (outcome.1, configuredFlags outcome)
  mulWithFlags x y :=
    let outcome := ExecFloat.Binary.mulWithStatus x y .nearestEven
    let lostZero := ExecFloat.Binary.isZero outcome.1 &&
      !ExecFloat.Binary.isZero x && !ExecFloat.Binary.isZero y
    (outcome.1, configuredFlags outcome ||| lostZero.toUInt8)
  divWithFlags x y :=
    let outcome := ExecFloat.Binary.divWithStatus x y .nearestEven
    let lostZero := ExecFloat.Binary.isZero outcome.1 && !ExecFloat.Binary.isZero x
    (outcome.1, configuredFlags outcome ||| lostZero.toUInt8)
  encode x := (ExecFloat.Binary.toRat? x).map QuotientCoefficients.scalar
  decode
    | .scalar x => some <| ExecFloat.Binary.ofModel <| Model.roundRatQ format x
  copyPrimal x _ := x

end Configured

end QuotientArithmetic
end TorchLean.Numeric
