/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import FloatLib.Floats.Formats.IEEE754.Native
public import FloatLib.Floats.Formats.BinaryInterchange.Configured.Rounding.Runtime

/-!
# Arithmetic for nested quotient rules

Checked operations retain range-loss information until the complete quotient has been evaluated.
The cold path evaluates the original finite coefficient trees over `Rat`, then rounds each
coefficient through FloatLib to the requested format. This is scoped to one quotient: it cannot
recover information lost before its inputs were formed.
-/

@[expose] public section

namespace TorchLean.Numeric

/-- Coefficients in the algebra generated by `n` commuting square-zero variables. -/
inductive QuotientCoefficients : Nat → Type where
  | scalar : Rat → QuotientCoefficients 0
  | dual {n : Nat} :
      QuotientCoefficients n → QuotientCoefficients n → QuotientCoefficients (n + 1)

namespace QuotientCoefficients

def primal : {n : Nat} → QuotientCoefficients n → Rat
  | _, .scalar x => x
  | _, .dual x _ => primal x

def add : {n : Nat} → QuotientCoefficients n → QuotientCoefficients n →
    QuotientCoefficients n
  | _, .scalar x, .scalar y => .scalar (x + y)
  | _, .dual x dx, .dual y dy => .dual (add x y) (add dx dy)

def sub : {n : Nat} → QuotientCoefficients n → QuotientCoefficients n →
    QuotientCoefficients n
  | _, .scalar x, .scalar y => .scalar (x - y)
  | _, .dual x dx, .dual y dy => .dual (sub x y) (sub dx dy)

def mul : {n : Nat} → QuotientCoefficients n → QuotientCoefficients n →
    QuotientCoefficients n
  | _, .scalar x, .scalar y => .scalar (x * y)
  | _, .dual x dx, .dual y dy => .dual (mul x y) (add (mul dx y) (mul x dy))

/-- The caller checks that the denominator's primal is nonzero before entering this recursion. -/
def div : {n : Nat} → QuotientCoefficients n → QuotientCoefficients n →
    QuotientCoefficients n
  | _, .scalar x, .scalar y => .scalar (x / y)
  | _, .dual x dx, .dual y dy =>
      let q := div x y
      .dual q (div (sub dx (mul q dy)) y)

end QuotientCoefficients

/--
Operations used inside one complete quotient, together with finite coefficient conversion.

Internal byte flags record nonfinite or subnormal results, including a nonzero product or quotient
rounded to zero. Zero means no range loss; recursive carriers combine flags with bitwise OR.
The checked-operation entrypoints expose the same Boolean result without converting at each
internal node. Unsupported carriers use the ordinary operations and do not supply a conversion.
-/
class QuotientArithmetic (α : Type) where
  supported : Bool := false
  depth : Nat := 0
  addWithFlags : α → α → α × UInt8
  subWithFlags : α → α → α × UInt8
  mulWithFlags : α → α → α × UInt8
  divWithFlags : α → α → α × UInt8
  encode : α → Option (QuotientCoefficients depth) := fun _ => none
  decode : QuotientCoefficients depth → Option α := fun _ => none
  /-- Copy the scalar primal's native sign of zero after replaying derivative coefficients. -/
  copyPrimal : α → α → α := fun _ y => y

instance (priority := low) {α : Type} [Add α] [Sub α] [Mul α] [Div α] :
    QuotientArithmetic α where
  addWithFlags x y := (x + y, 0)
  subWithFlags x y := (x - y, 0)
  mulWithFlags x y := (x * y, 0)
  divWithFlags x y := (x / y, 0)

namespace QuotientArithmetic

@[inline] def addChecked {α : Type} [ops : QuotientArithmetic α] (x y : α) : α × Bool :=
  let (value, flags) := ops.addWithFlags x y
  (value, 0 < flags)

@[inline] def subChecked {α : Type} [ops : QuotientArithmetic α] (x y : α) : α × Bool :=
  let (value, flags) := ops.subWithFlags x y
  (value, 0 < flags)

@[inline] def mulChecked {α : Type} [ops : QuotientArithmetic α] (x y : α) : α × Bool :=
  let (value, flags) := ops.mulWithFlags x y
  (value, 0 < flags)

@[inline] def divChecked {α : Type} [ops : QuotientArithmetic α] (x y : α) : α × Bool :=
  let (value, flags) := ops.divWithFlags x y
  (value, 0 < flags)

/--
Replay only finite input trees with an invertible denominator.

Only coefficient conversion crosses this cold boundary, leaving the checked arithmetic
operations available for specialization in the caller.
-/
@[noinline] def replay? {α : Type} {depth : Nat}
    (encode : α → Option (QuotientCoefficients depth))
    (decode : QuotientCoefficients depth → Option α) (x y : α) : Option α := do
  let a ← encode x
  let b ← encode y
  if b.primal == 0 then none else decode (QuotientCoefficients.div a b)

def finiteRat? (bits : UInt64) : Option Rat :=
  FloatLib.Floats.ExecFloat.Binary.toRat?
    (FloatLib.Floats.ExecFloat.Binary.ofBits64 bits)

def roundFloat (value : Rat) : Float :=
  FloatLib.Floats.ExecFloat.Binary.toFloat <|
    FloatLib.Floats.ExecFloat.Binary.ofModel <|
      FloatLib.Floats.Formats.BinaryInterchange.Model.roundRat
        FloatLib.Floats.Formats.BinaryInterchange.FloatFormat.binary64
        (value.num < 0) value.num.natAbs value.den

def roundFloat32 (value : Rat) : Float32 :=
  FloatLib.Floats.ExecFloat.Binary.toFloat32 <|
    FloatLib.Floats.ExecFloat.Binary.ofModel <|
      FloatLib.Floats.Formats.BinaryInterchange.Model.roundRat
        FloatLib.Floats.Formats.BinaryInterchange.FloatFormat.binary32
        (value.num < 0) value.num.natAbs value.den

-- Native constants are initialized once, outside all checked operations.
@[noinline] def zero64 : Float := Float.ofBits 0
@[noinline] def minNormal64 : Float := Float.ofBits 0x0010000000000000
@[noinline] def negMinNormal64 : Float := Float.ofBits 0x8010000000000000

@[noinline] def zero32 : Float32 := Float32.ofBits 0
@[noinline] def minNormal32 : Float32 := Float32.ofBits 0x00800000
@[noinline] def negMinNormal32 : Float32 := Float32.ofBits 0x80800000

-- The supplied zero predicate is an actual operation and the specialization key.
-- For finite values x - x is zero; infinities and NaNs instead produce NaN.
-- Excluding zero from the interval (-minNormal, minNormal) leaves the subnormals.
@[inline] def zeroFlag64 (x : Float) : UInt8 := (x == zero64).toUInt8

-- A finite self-difference is zero; a nonfinite self-difference is NaN.
-- Reflexive equality of that difference detects NaN without a floating zero constant.
@[inline] def nonfiniteFlag64 (x : Float) : UInt8 :=
  let difference := x - x
  (difference == difference).toUInt8 ^^^ 1

@[inline] def rangeFlags64Using (zero : Float → UInt8) (x : Float) : UInt8 :=
  if ((decide (negMinNormal64 < x)).toUInt8 &&&
      (decide (x < minNormal64)).toUInt8) == 1 then
    zero x ^^^ 1
  else nonfiniteFlag64 x

@[inline] def rangeFlags64 (x : Float) : UInt8 :=
  rangeFlags64Using zeroFlag64 x

@[inline] def exposed64 (x : Float) : Bool := 0 < rangeFlags64 x

-- Only predicates cross this boundary. Value-producing arithmetic remains inline.
-- The open interval contains only finite values. Its branch needs zero checks;
-- outside it, only nonfiniteness can raise a flag.
@[noinline, specialize zero] def addSub64Flags (zero : Float → UInt8)
    (z : Float) : UInt8 :=
  rangeFlags64Using zero z

/-- Range flags for the actual native product `z = x * y`, using native zero equality.
The open subnormal interval includes zero; nonzero inputs detect a product rounded to zero.
This formula requires the actual product, not an independently supplied third value. -/
@[noinline, specialize zero] def product64Flags (zero : Float → UInt8)
    (x y z : Float) : UInt8 :=
  if ((decide (negMinNormal64 < z)).toUInt8 &&&
      (decide (z < minNormal64)).toUInt8) == 1 then
    (zero x ^^^ 1) &&& (zero y ^^^ 1)
  else nonfiniteFlag64 z

/-- Range flags for the actual native quotient `z = x / y`, using native zero equality.
A zero denominator already makes the result nonfinite. A zero or subnormal result with a
nonzero numerator requires replay. This formula assumes `z` is the actual division result. -/
@[noinline, specialize zero] def quotient64Flags (zero : Float → UInt8)
    (x z : Float) : UInt8 :=
  if ((decide (negMinNormal64 < z)).toUInt8 &&&
      (decide (z < minNormal64)).toUInt8) == 1 then
    zero x ^^^ 1
  else nonfiniteFlag64 z

@[inline] def add64WithFlags (x y : Float) : Float × UInt8 :=
  let z := x + y
  (z, addSub64Flags zeroFlag64 z)

@[inline] def sub64WithFlags (x y : Float) : Float × UInt8 :=
  let z := x - y
  (z, addSub64Flags zeroFlag64 z)

@[inline] def mul64WithFlags (x y : Float) : Float × UInt8 :=
  let z := x * y
  (z, product64Flags zeroFlag64 x y z)

@[inline] def div64WithFlags (x y : Float) : Float × UInt8 :=
  let z := x / y
  (z, quotient64Flags zeroFlag64 x z)

@[inline] def zeroFlag32 (x : Float32) : UInt8 := (x == zero32).toUInt8

-- A finite self-difference is zero; a nonfinite self-difference is NaN.
-- Reflexive equality of that difference detects NaN without a floating zero constant.
@[inline] def nonfiniteFlag32 (x : Float32) : UInt8 :=
  let difference := x - x
  (difference == difference).toUInt8 ^^^ 1

@[inline] def rangeFlags32Using (zero : Float32 → UInt8) (x : Float32) : UInt8 :=
  if ((decide (negMinNormal32 < x)).toUInt8 &&&
      (decide (x < minNormal32)).toUInt8) == 1 then
    zero x ^^^ 1
  else nonfiniteFlag32 x

@[inline] def rangeFlags32 (x : Float32) : UInt8 :=
  rangeFlags32Using zeroFlag32 x

@[inline] def exposed32 (x : Float32) : Bool := 0 < rangeFlags32 x

-- Only predicates cross this boundary. Value-producing arithmetic remains inline.
@[noinline, specialize zero] def addSub32Flags (zero : Float32 → UInt8)
    (z : Float32) : UInt8 :=
  rangeFlags32Using zero z

/-- Range flags for the actual native product `z = x * y`, using native zero equality.
The open subnormal interval includes zero; nonzero inputs detect a product rounded to zero.
This formula requires the actual product, not an independently supplied third value. -/
@[noinline, specialize zero] def product32Flags (zero : Float32 → UInt8)
    (x y z : Float32) : UInt8 :=
  if ((decide (negMinNormal32 < z)).toUInt8 &&&
      (decide (z < minNormal32)).toUInt8) == 1 then
    (zero x ^^^ 1) &&& (zero y ^^^ 1)
  else nonfiniteFlag32 z

/-- Range flags for the actual native quotient `z = x / y`, using native zero equality.
A zero denominator already makes the result nonfinite. A zero or subnormal result with a
nonzero numerator requires replay. This formula assumes `z` is the actual division result. -/
@[noinline, specialize zero] def quotient32Flags (zero : Float32 → UInt8)
    (x z : Float32) : UInt8 :=
  if ((decide (negMinNormal32 < z)).toUInt8 &&&
      (decide (z < minNormal32)).toUInt8) == 1 then
    zero x ^^^ 1
  else nonfiniteFlag32 z

@[inline] def add32WithFlags (x y : Float32) : Float32 × UInt8 :=
  let z := x + y
  (z, addSub32Flags zeroFlag32 z)

@[inline] def sub32WithFlags (x y : Float32) : Float32 × UInt8 :=
  let z := x - y
  (z, addSub32Flags zeroFlag32 z)

@[inline] def mul32WithFlags (x y : Float32) : Float32 × UInt8 :=
  let z := x * y
  (z, product32Flags zeroFlag32 x y z)

@[inline] def div32WithFlags (x y : Float32) : Float32 × UInt8 :=
  let z := x / y
  (z, quotient32Flags zeroFlag32 x z)

@[inline] instance : QuotientArithmetic Float where
  supported := true
  addWithFlags := add64WithFlags
  subWithFlags := sub64WithFlags
  mulWithFlags := mul64WithFlags
  divWithFlags := div64WithFlags
  encode x := (finiteRat? x.toBits).map QuotientCoefficients.scalar
  decode | .scalar x => some (roundFloat x)
  copyPrimal x _ := x

@[inline] instance : QuotientArithmetic Float32 where
  supported := true
  addWithFlags := add32WithFlags
  subWithFlags := sub32WithFlags
  mulWithFlags := mul32WithFlags
  divWithFlags := div32WithFlags
  encode x := (finiteRat? x.toFloat.toBits).map QuotientCoefficients.scalar
  decode | .scalar x => some (roundFloat32 x)
  copyPrimal x _ := x

section Configured

open FloatLib.Floats.Formats.BinaryInterchange
open FloatLib.Floats (ExecFloat)

variable {format : FloatFormat} {plan : Configured.StoragePlan format} {code : Type}
    [ExecFloat.ModelCodec plan (Model format) code]

local notation "Value" => ExecFloat (Configured.Family format code plan)

/--
FloatLib exception status plus the stricter range predicate needed by a nested quotient.

IEEE underflow requires inexactness. An exact subnormal intermediate must also trigger replay,
since subsequent multiplication or division can lose coefficients. Ordinary inexact rounding
alone does not trigger replay.
-/
def configuredFlags (outcome : Value × Model.IEEEStatus) : UInt8 :=
  let (value, status) := outcome
  (status.invalid || status.divideByZero || status.overflow || status.underflow ||
    !ExecFloat.Binary.isFinite value || ExecFloat.Binary.isSubnormal value).toUInt8

/--
Configured IEEE values use FloatLib's nearest-even operations and exact finite decoder.

The complete derivative tree is replayed by the recursive `Dual` instance. Every coefficient is
rounded independently to the original descriptor and storage plan, including formats wider than
binary64. Finite-only encodings are not enabled: their saturation policy would require a separate
derivative contract. True coefficients outside the IEEE range may still round to zero or infinity.
-/
instance configured : QuotientArithmetic Value where
  supported := format.isIEEE
  addWithFlags x y :=
    let outcome := ExecFloat.Binary.addWithStatus x y .nearestEven
    (outcome.1, configuredFlags outcome)
  subWithFlags x y :=
    let outcome := ExecFloat.Binary.subWithStatus x y .nearestEven
    (outcome.1, configuredFlags outcome)
  mulWithFlags x y :=
    let outcome := ExecFloat.Binary.mulWithStatus x y .nearestEven
    let lostZero := ExecFloat.Binary.isZero outcome.1 &&
      !ExecFloat.Binary.isZero x && !ExecFloat.Binary.isZero y
    (outcome.1, configuredFlags outcome ||| lostZero.toUInt8)
  divWithFlags x y :=
    let outcome := ExecFloat.Binary.divWithStatus x y .nearestEven
    let lostZero := ExecFloat.Binary.isZero outcome.1 && !ExecFloat.Binary.isZero x
    (outcome.1, configuredFlags outcome ||| lostZero.toUInt8)
  encode x := (ExecFloat.Binary.toRat? x).map QuotientCoefficients.scalar
  decode
    | .scalar x => some <| ExecFloat.Binary.ofModel <|
        Model.roundRat format (x.num < 0) x.num.natAbs x.den
  copyPrimal x _ := x

end Configured

end QuotientArithmetic
end TorchLean.Numeric
