/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import NN.API.Verification.Lowering
public import NN.Core.ExternalProcess
public import NN.Verification.Robustness.TopLabel
public import NN.Verification.Util.Json
public import NN.Verification.Util.Tensor
public import NN.Runtime.Autograd.Model.Metrics

/-!
# Digits certified robustness

Certified accuracy for a linear classifier on sklearn's digits dataset.

Workflow:
- Train a small linear classifier on sklearn's digits (8x8) in Python and export:
  - weights JSON (`digits_linear_weights.json`)
  - test dataset JSON (`digits_test.json`)
- In Lean, load the weights + dataset and compute certified accuracy under an $\ell^\infty$ input
  box using:
  - IBP (`runIBP`)
  - CROWN (`outputBoxCROWN?`), which takes each lower endpoint from the lower affine form and each
    upper endpoint from the upper form

Run:
  `lake exe verify -- digits`
  `lake exe verify -- digits --eps=0.02 --max=360`
  `lake exe verify -- digits --arithmetic ieee --eps=0.02`
  `lake exe verify -- digits-train-certify --epochs=50 --eps=0.02 --max=100`

Regenerate assets:
  `python3 scripts/verification/robustness/train_digits_linear.py`
-/

@[expose] public section


namespace NN.Verification.Robustness.Digits

open Spec TorchLean
open TorchLean.Tensor

open NN.MLTheory.CROWN.Graph
open NN.MLTheory.CROWN
open Lean
open Json
open NN.Verification.Json

/-- Flattened input dimension for sklearn digits (8×8). -/
def inDim : Nat := 64
/-- Number of classes (digits 0..9). -/
def outDim : Nat := 10

/-- Weight shape for a linear classifier $y=Wx+b$ (10×64). -/
def wShape : Shape := [outDim, inDim]
/-- Bias shape for a linear classifier (10). -/
def bShape : Shape := [outDim]
/-- Input shape (64). -/
def xShape : Shape := [inDim]
/-- Output/logit shape (10). -/
def yShape : Shape := [outDim]

/-- Parameter shapes list used by the lowered TorchLean program (`[W, b]`). -/
def paramShapes : List Shape := [wShape, bShape]

/-- Bundled sklearn-digits linear classifier weights. -/
def defaultWeightsPath : String :=
  "NN/Examples/Verification/Robustness/digits_linear_weights.json"

/-- Bundled sklearn-digits test set. -/
def defaultDatasetPath : String :=
  "NN/Examples/Verification/Robustness/digits_test.json"

/-- Python exporter used by the train-then-certify command. -/
def defaultTrainScript : String :=
  "scripts/verification/robustness/train_digits_linear.py"

/-- CLI options for the digits certified-accuracy workflow. -/
structure Options where
  /-- Weights JSON path (PyTorch export). -/
  weights : String := defaultWeightsPath
  /-- Dataset JSON path (PyTorch export). -/
  dataset : String := defaultDatasetPath
  /-- $L^\infty$ perturbation radius around each input example. -/
  eps     : Float  := 0.02
  /-- Max number of examples to evaluate (for local checks). -/
  max     : Nat    := 100
  deriving Repr

/-- Options for the train → lower → certify report command. -/
structure TrainCertifyOptions where
  /-- Lean side certification options after Python exports the model and dataset. -/
  certify : Options := {}
  /-- Python trainer script path. -/
  script : String := defaultTrainScript
  /-- Reproducibility seed forwarded to the trainer. -/
  seed : Nat := 0
  /-- Number of Python training epochs. -/
  epochs : Nat := 200
  /-- Python trainer batch size. -/
  batch : Nat := 128
  /-- Python trainer learning rate. -/
  lr : Float := 1e-2
  /-- Test split fraction used by the trainer. -/
  testSize : Float := 0.2
  /-- Number of test examples exported by the trainer. -/
  maxTest : Nat := 360
  deriving Repr

/-- Usage string printed on `--help` / `-h`. -/
def usage : String :=
  String.intercalate "\n" [
    "Usage:",
    ("  lake exe verify -- digits [--weights=PATH.json] " ++
      "[--dataset=PATH.json] [--eps=0.02] [--max=100]"),
    ("  lake exe verify -- digits-train-certify [trainer flags] " ++
      "[--weights=PATH.json] [--dataset=PATH.json] [--eps=0.02] [--max=100]"),
    "",
    "Notes:",
    "  - Arithmetic flags are also accepted (e.g. --arithmetic ieee).",
    "  - digits-train-certify runs the Python trainer, then lowers and certifies in Lean.",
    s!"  - Assets are generated by: python3 {defaultTrainScript}"
  ]

/-- A negative or NaN radius would give an empty input box, which certifies vacuously. -/
def checkEps (eps : Float) : Except String Unit :=
  unless eps ≥ 0 && eps.isFinite do
    throw s!"--eps must be a finite nonnegative radius, got {eps}"

/--
Consume the certification flags shared by both digits commands (after `--` stripping and the
`--help` check), returning the remaining arguments. Flags are extracted by key, so the caller may
consume its own flags from the remainder in any order.
-/
def takeCertifyFlags (args : List String) : Except String (Options × List String) := do
  let args := TorchLean.CLI.dropDashDash args
  if TorchLean.CLI.hasHelp args then
    throw usage
  let (weights, args) ← TorchLean.CLI.takeFlagValue args "weights" (default := defaultWeightsPath)
  let (dataset, args) ← TorchLean.CLI.takeFlagValue args "dataset" (default := defaultDatasetPath)
  let (eps, args) ← TorchLean.CLI.takeFloatFlag args "eps" (default := 0.02)
  checkEps eps
  let (max, args) ← TorchLean.CLI.takeNatFlag args "max" (default := 100)
  pure ({ weights := weights, dataset := dataset, eps := eps, max := max }, args)

/-- Parse CLI args into `Options` (returns `usage` as the error message on `--help`). -/
def parseArgs (args : List String) : Except String Options := do
  let (options, args) ← takeCertifyFlags args
  TorchLean.CLI.checkNoArgs args
  pure options

/-- Parse the combined trainer/certifier CLI for `digits-train-certify`. -/
def parseTrainCertifyArgs (args : List String) : Except String TrainCertifyOptions := do
  let (certify, args) ← takeCertifyFlags args
  let (script, args) ← TorchLean.CLI.takeFlagValue args "script" (default := defaultTrainScript)
  let (seed, args) ← TorchLean.CLI.takeNatFlag args "seed" (default := 0)
  let (epochs, args) ← TorchLean.CLI.takeNatFlag args "epochs" (default := 200)
  let (batch, args) ← TorchLean.CLI.takeNatFlag args "batch" (default := 128)
  let (lr, args) ← TorchLean.CLI.takeFloatFlag args "lr" (default := 1e-2)
  let (testSize, args) ← TorchLean.CLI.takeFloatFlag args "test-size" (default := 0.2)
  let (maxTest, args) ← TorchLean.CLI.takeNatFlag args "max-test" (default := 360)
  TorchLean.CLI.checkNoArgs args
  pure {
    certify := certify
    script := script
    seed := seed
    epochs := epochs
    batch := batch
    lr := lr
    testSize := testSize
    maxTest := maxTest
  }

/-- Trainer command-line arguments generated from `TrainCertifyOptions`. -/
def trainerArgs (options : TrainCertifyOptions) : Array String :=
  #[
    options.script,
    "--seed", toString options.seed,
    "--epochs", toString options.epochs,
    "--lr", toString options.lr,
    "--batch", toString options.batch,
    "--test-size", toString options.testSize,
    "--max-test", toString options.maxTest,
    "--out-weights", options.certify.weights,
    "--out-dataset", options.certify.dataset
  ]

/-- TorchLean program for the linear classifier $y=Wx+b$. -/
def classifier {α : Type} [TorchLean.Storage α] [Context α] :
    TorchLean.Runtime.Program α (paramShapes ++ [xShape]) yShape :=
  fun {m} _ _ =>
    fun w b x =>
      (TorchLean.Runtime.linear
        (m := m) (α := α)
        (batchShape := []) (inputWidth := inDim) (outputWidth := outDim) w b x
        : m (TorchLean.Runtime.ValueRef (m := m) (α := α) yShape))

/-- Load linear classifier weights exported from PyTorch into a typed `LinearSpec`. -/
def loadWeights (path : String) : IO (Spec.LinearSpec Float inDim outDim) := do
  let j ← readJsonObjectFile path
  let wJ ← expectField j "layers.0.weight" "weights"
  let bJ ← expectField j "layers.0.bias" "weights"
  let wArr ← expectFiniteFloatMatrix wJ "layers.0.weight"
  let bArr ← expectFiniteFloatArray bJ "layers.0.bias"
  let some w := NN.Verification.Util.Tensor.matOfArray outDim inDim wArr
    | throw <| IO.userError
        s!"layers.0.weight must be a float matrix of shape [{outDim}][{inDim}]"
  let b ← NN.Verification.Util.Tensor.requireVecOfArray "layers.0.bias" outDim bArr
  pure { weights := w, bias := b }

/-- Load the digits test dataset exported from Python (JSON). -/
def loadDataset (path : String) : IO (Array (Tensor Float xShape × Nat)) := do
  let j ← readJsonObjectFile path
  let examples ←
    match ← optionalField? j "examples" "dataset" with
    | none => pure #[]
    | some examplesJ => expectArray examplesJ "dataset.examples"
  let mut out : Array (Tensor Float xShape × Nat) := #[]
  for e in examples do
    let eo ← expectObject e "dataset example"
    let xJ ← expectField eo "x" "dataset example"
    let y ← expectFieldNat eo "y" "dataset example"
    let vec ← expectFiniteFloatArray xJ "dataset example.x"
    let xT ← NN.Verification.Util.Tensor.requireVecOfArray "dataset example.x" inDim vec
    out := out.push (xT, y)
  pure out

/-- Running counters for the digits certified-accuracy workflow. -/
structure Report where
  /-- Number of examples checked. -/
  total : Nat := 0
  /-- Number of clean examples classified correctly by the exported model. -/
  nominalOk : Nat := 0
  /-- Number of examples certified by interval bound propagation. -/
  ibpOk : Nat := 0
  /-- Number of examples certified by the affine CROWN pass. -/
  crownOk : Nat := 0
  deriving Repr

/--
The certified input box: the binary64 `ℓ∞` ball around `x`, rounded outward by `FlatBox.lInfBall`,
clipped to the pixel range `[0, 1]`, and converted to `α` with the directed rounding of
`TorchLean.Runtime.ofFloatDirected`. It contains every real input within `eps` of the binary64
center that lies in `[0, 1]`.
-/
def certifiedInputBox {α : Type} [TorchLean.Storage α] [Context α] [TorchLean.Runtime.FromFloat α]
    (x : Tensor Float xShape) (eps : Float) : FlatBox α :=
  let ball := FlatBox.lInfBall (α := Float) x eps
  let clip (v : Float) : Float := min 1 (max 0 v)
  { dim := ball.dim
    lo := TorchLean.Tensor.map
      (fun v => TorchLean.Runtime.ofFloatDirected (α := α) false (clip v)) ball.lo
    hi := TorchLean.Tensor.map
      (fun v => TorchLean.Runtime.ofFloatDirected (α := α) true (clip v)) ball.hi }

/--
CROWN verdict for `label` on the input box `xB`.

The lower endpoint of each logit comes from the lower affine form and the upper endpoint from the
upper form. The minimum of the upper form over the box is not a lower bound when the two forms
differ, so reading both endpoints from one form can certify a misclassified input.
-/
def crownCertifiesLabel {α : Type} [TorchLean.Storage α] [Context α]
    [BoundOps α] [NonlinearBoundOps α]
    (g : NN.IR.Graph) (ps : ParamStore α) (xB : FlatBox α) (inputId outputId label : Nat) :
    Except String Bool := do
  let outB ← outputBoxCROWN? (α := α) g ps xB inputId outputId xB.dim
  pure <| TopLabel.strictTopLabelBy outB.dim label
    (fun i => outB.lo.getScalar i) (fun i => outB.hi.getScalar i) Context.gtBool

/--
Run the certified-accuracy evaluation once, under a chosen scalar backend `α`.

This lowers the linear classifier to the verifier IR, then checks each example's $L^\infty$ box
using IBP and two-sided CROWN output bounds.
-/
def runOnce {α : Type} [TorchLean.Storage α] [Context α]
    [BoundOps α] [NonlinearBoundOps α] [ToString α]
    [TorchLean.Runtime.FromFloat α] (options : Options) : IO Report := do
  let cast : Float → α := TorchLean.Runtime.ofFloat
  let linF ← loadWeights options.weights
  let examples0 ← loadDataset options.dataset
  let examples := examples0.take options.max

  let params : TorchLean.nn.State α paramShapes :=
    TorchLean.nn.State.empty
      |>.push (TorchLean.Tensor.map cast linF.weights)
      |>.push (TorchLean.Tensor.map cast linF.bias)

  let lowered ← IO.ofExcept <|
    TorchLean.Verification.lowerProgramToIR (α := α) (classifier (α := α)) params

  IO.println s!"[digits] lowered IR nodes: {lowered.graph.nodes.size}"

  let mut report : Report := {}

  for (xF, yNat) in examples do
    report := { report with total := report.total + 1 }

    let yF : Tensor Float yShape := Spec.linearSpec (α := Float) linF xF
    if (TorchLean.Metrics.argmax? (α := Float) yF).map Fin.val = some yNat then
      report := { report with nominalOk := report.nominalOk + 1 }

    let xB : FlatBox α := certifiedInputBox xF options.eps

    let ps : ParamStore α := lowered.seedInputBox xB

    let ibp := lowered.runIBP ps
    let outB ← lowered.outputBoxOrThrow ibp
    if hOut : outB.dim = outDim then
      let loY : Tensor α yShape := outB.loAsDim hOut
      let hiY : Tensor α yShape := outB.hiAsDim hOut
      if TopLabel.certifiesLabelFromTensorBounds (α := α) loY hiY yNat then
        report := { report with ibpOk := report.ibpOk + 1 }
    else
      throw <| IO.userError s!"Unexpected output dim {outB.dim} (expected {outDim})"

    match crownCertifiesLabel (α := α) lowered.graph ps xB
        lowered.inputId lowered.outputId yNat with
    | .ok true => report := { report with crownOk := report.crownOk + 1 }
    | .ok false => pure ()
    | .error e => throw <| IO.userError s!"CROWN failed: {e}"

  IO.println s!"[digits] examples={report.total} eps={options.eps}"
  IO.println s!"[digits] nominal accuracy: {report.nominalOk}/{report.total}"
  IO.println s!"[digits] certified (IBP):   {report.ibpOk}/{report.total}"
  IO.println s!"[digits] certified (CROWN): {report.crownOk}/{report.total}"
  pure report

/--
CLI entry point for the digits certified-robustness workflow.

This is wired into `lake exe verify -- digits`.
-/
def main (args : List String) : IO Unit := do
  IO.println "== TorchLean digits certified robustness =="
  let (arithmetic, rest) ← IO.ofExcept (TorchLean.Runtime.Arithmetic.parseAndStrip args)
  TorchLean.Runtime.Arithmetic.log arithmetic
  let options ← IO.ofExcept (parseArgs rest)
  NN.Verification.Builtin.withBoundArithmetic arithmetic
    (fun {α} _ _ _ _ _ _ => do
      let _ ← runOnce (α := α) options
      pure ())

/--
Train a fresh digits classifier, lower it through the TorchLean verifier path, and certify it.

The Python trainer is an artifact producer only. Lean still parses the exported JSON, lowers the
TorchLean program to verifier IR, runs IBP and affine CROWN bounds, and prints the certification
report from the checked artifacts.
-/
def mainTrainThenCertify (args : List String) : IO Unit := do
  IO.println "== TorchLean digits train → lower → certify =="
  let (arithmetic, rest) ← IO.ofExcept (TorchLean.Runtime.Arithmetic.parseAndStrip args)
  TorchLean.Runtime.Arithmetic.log arithmetic
  let options ← IO.ofExcept (parseTrainCertifyArgs rest)

  let pythonCmd ← TorchLean.External.Process.resolveCmdFromEnv "TORCHLEAN_PYTHON" "python3"
  let python ← TorchLean.External.Process.ensureCmdAvailable
    "Python 3" pythonCmd #["--version"] (some "TORCHLEAN_PYTHON")
  IO.println s!"[digits] training/export script: {options.script}"
  IO.println s!"[digits] exported weights: {options.certify.weights}"
  IO.println s!"[digits] exported dataset: {options.certify.dataset}"
  let out ← TorchLean.External.Process.run
    (ctx := "digits train/export")
    (cmd := python)
    (args := trainerArgs options)
    (cwd := some ".")
  let trainLog := out.trimAscii.toString
  if !trainLog.isEmpty then
    IO.println trainLog
  IO.println "[digits] Python export complete; entering Lean certification path."

  NN.Verification.Builtin.withBoundArithmetic arithmetic
    (fun {α} _ _ _ _ _ _ => do
      let report ← runOnce (α := α) options.certify
      if report.total = 0 then
        throw <| IO.userError "digits train-then-certify produced an empty report"
      IO.println
        (s!"[digits] report: total={report.total}, nominal={report.nominalOk}, " ++
          s!"ibp={report.ibpOk}, crown={report.crownOk}"))

end NN.Verification.Robustness.Digits
