/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import NN.API.Verification.Lowering
public import NN.Core.ExternalProcess
public import NN.Verification.Robustness.TopLabel
public import NN.Verification.Util.Json
public import NN.Verification.Util.Tensor
public import NN.Runtime.Autograd.Model.Metrics
public import NN.Verification.Builtin.Lowering
public import NN.API.Runtime -- shake: keep

/-!
# Digits certified robustness

Certified accuracy for a linear classifier on sklearn's digits dataset.

Workflow:
- Train a small linear classifier on sklearn's digits (8x8) in Python and export:
  - weights JSON (`digits_linear_weights.json`)
  - test dataset JSON (`digits_test.json`)
- In Lean, load the weights + dataset and compute certified accuracy under an $\ell^\infty$ input
  box using:
  - IBP (`runIBP`)
  - a simple CROWN/affine pass (`runAffine` + `AffineVec.evalOnBox`)

Run:
  `lake exe verify -- digits`
  `lake exe verify -- digits --eps=0.02 --max=360`
  `lake exe verify -- digits --arithmetic ieee --eps=0.02`
  `lake exe verify -- digits-train-certify --epochs=50 --eps=0.02 --max=100`

Regenerate assets:
  `python3 scripts/verification/robustness/train_digits_linear.py`
-/

@[expose] public section


namespace NN.Verification.Robustness.Digits

open Spec TorchLean
open TorchLean.Tensor

open NN.MLTheory.CROWN.Graph
open NN.MLTheory.CROWN
open Lean
open Json
open NN.Verification.Json

/-- Flattened input dimension for sklearn digits (8×8). -/
def inDim : Nat := 64
/-- Number of classes (digits 0..9). -/
def outDim : Nat := 10

/-- Weight shape for a linear classifier $y=Wx+b$ (10×64). -/
def WShape : Shape := [outDim, inDim]
/-- Bias shape for a linear classifier (10). -/
def bShape : Shape := [outDim]
/-- Input shape (64). -/
def xShape : Shape := [inDim]
/-- Output/logit shape (10). -/
def yShape : Shape := [outDim]

/-- Parameter shapes list used by the lowered TorchLean program (`[W, b]`). -/
def paramShapes : List Shape := [WShape, bShape]

/-- Bundled sklearn-digits linear classifier weights. -/
def defaultWeightsPath : String :=
  "NN/Examples/Verification/Robustness/digits_linear_weights.json"

/-- Bundled sklearn-digits test set. -/
def defaultDatasetPath : String :=
  "NN/Examples/Verification/Robustness/digits_test.json"

/-- Python exporter used by the train-then-certify command. -/
def defaultTrainScript : String :=
  "scripts/verification/robustness/train_digits_linear.py"

/-- CLI options for the digits certified-accuracy workflow. -/
structure Options where
  /-- Weights JSON path (PyTorch export). -/
  weights : String := defaultWeightsPath
  /-- Dataset JSON path (PyTorch export). -/
  dataset : String := defaultDatasetPath
  /-- $L^\infty$ perturbation radius around each input example. -/
  eps     : Float  := 0.02
  /-- Max number of examples to evaluate (for local checks). -/
  max     : Nat    := 100
  deriving Repr

/-- Options for the train → lower → certify report command. -/
structure TrainCertifyOptions where
  /-- Lean side certification options after Python exports the model and dataset. -/
  certify : Options := {}
  /-- Python trainer script path. -/
  script : String := defaultTrainScript
  /-- Reproducibility seed forwarded to the trainer. -/
  seed : Nat := 0
  /-- Number of Python training epochs. -/
  epochs : Nat := 200
  /-- Python trainer batch size. -/
  batch : Nat := 128
  /-- Python trainer learning rate. -/
  lr : Float := 1e-2
  /-- Test split fraction used by the trainer. -/
  testSize : Float := 0.2
  /-- Number of test examples exported by the trainer. -/
  maxTest : Nat := 360
  deriving Repr

/-- Usage string printed on `--help` / `-h`. -/
def usage : String :=
  String.intercalate "\n" [
    "Usage:",
    ("  lake exe verify -- digits [--weights=PATH.json] " ++
      "[--dataset=PATH.json] [--eps=0.02] [--max=100]"),
    ("  lake exe verify -- digits-train-certify [trainer flags] " ++
      "[--weights=PATH.json] [--dataset=PATH.json] [--eps=0.02] [--max=100]"),
    "",
    "Notes:",
    "  - Arithmetic flags are also accepted (e.g. --arithmetic ieee).",
    "  - digits-train-certify runs the Python trainer, then lowers and certifies in Lean.",
    s!"  - Assets are generated by: python3 {defaultTrainScript}"
  ]

/-- Parse CLI args into `Options` (returns `usage` as the error message on `--help`). -/
def parseArgs (args : List String) : Except String Options := do
  let args := TorchLean.CLI.dropDashDash args
  if TorchLean.CLI.hasHelp args then
    throw usage
  let (weights, args) ← TorchLean.CLI.takeFlagValue args "weights" (default := defaultWeightsPath)
  let (dataset, args) ← TorchLean.CLI.takeFlagValue args "dataset" (default := defaultDatasetPath)
  let (eps, args) ← TorchLean.CLI.takeFloatFlag args "eps" (default := 0.02)
  let (max, args) ← TorchLean.CLI.takeNatFlag args "max" (default := 100)
  TorchLean.CLI.checkNoArgs args
  pure { weights := weights, dataset := dataset, eps := eps, max := max }

/-- Parse the combined trainer/certifier CLI for `digits-train-certify`. -/
def parseTrainCertifyArgs (args : List String) : Except String TrainCertifyOptions := do
  let args := TorchLean.CLI.dropDashDash args
  if TorchLean.CLI.hasHelp args then
    throw usage
  let (script, args) ← TorchLean.CLI.takeFlagValue args "script" (default := defaultTrainScript)
  let (weights, args) ← TorchLean.CLI.takeFlagValue args "weights" (default := defaultWeightsPath)
  let (dataset, args) ← TorchLean.CLI.takeFlagValue args "dataset" (default := defaultDatasetPath)
  let (eps, args) ← TorchLean.CLI.takeFloatFlag args "eps" (default := 0.02)
  let (max, args) ← TorchLean.CLI.takeNatFlag args "max" (default := 100)
  let (seed, args) ← TorchLean.CLI.takeNatFlag args "seed" (default := 0)
  let (epochs, args) ← TorchLean.CLI.takeNatFlag args "epochs" (default := 200)
  let (batch, args) ← TorchLean.CLI.takeNatFlag args "batch" (default := 128)
  let (lr, args) ← TorchLean.CLI.takeFloatFlag args "lr" (default := 1e-2)
  let (testSize, args) ← TorchLean.CLI.takeFloatFlag args "test-size" (default := 0.2)
  let (maxTest, args) ← TorchLean.CLI.takeNatFlag args "max-test" (default := 360)
  TorchLean.CLI.checkNoArgs args
  pure {
    certify := { weights := weights, dataset := dataset, eps := eps, max := max }
    script := script
    seed := seed
    epochs := epochs
    batch := batch
    lr := lr
    testSize := testSize
    maxTest := maxTest
  }

/-- Trainer command-line arguments generated from `TrainCertifyOptions`. -/
def trainerArgs (options : TrainCertifyOptions) : Array String :=
  #[
    options.script,
    "--seed", toString options.seed,
    "--epochs", toString options.epochs,
    "--lr", toString options.lr,
    "--batch", toString options.batch,
    "--test-size", toString options.testSize,
    "--max-test", toString options.maxTest,
    "--out-weights", options.certify.weights,
    "--out-dataset", options.certify.dataset
  ]

/-- TorchLean program for the linear classifier $y=Wx+b$. -/
def classifier {α : Type} [TorchLean.Storage α] [Context α] :
    TorchLean.Runtime.Program α (paramShapes ++ [xShape]) yShape :=
  fun {m} _ _ =>
    fun w b x =>
      (TorchLean.Runtime.linear
        (m := m) (α := α)
        (batchShape := []) (inputWidth := inDim) (outputWidth := outDim) w b x
        : m (TorchLean.Runtime.ValueRef (m := m) (α := α) yShape))

/-- Load linear classifier weights exported from PyTorch into a typed `LinearSpec`. -/
def loadWeights (path : String) : IO (Spec.LinearSpec Float inDim outDim) := do
  let j ← readJsonObjectFile path
  match j with
  | .obj o =>
      let wJ ←
        match o.get? "layers.0.weight" with
        | some jw => pure jw
        | none => throw <| IO.userError "Missing weights key: layers.0.weight"
      let bJ ←
        match o.get? "layers.0.bias" with
        | some jb => pure jb
        | none => throw <| IO.userError "Missing weights key: layers.0.bias"
      let wArr ← NN.Verification.Json.expectFiniteFloatMatrix wJ "layers.0.weight"
      let bArr ← NN.Verification.Json.expectFiniteFloatArray bJ "layers.0.bias"
      let some w := NN.Verification.Util.Tensor.matOfArray outDim inDim wArr
        | throw <| IO.userError "layers.0.weight must be a float matrix of shape [10][64]"
      let some b := NN.Verification.Util.Tensor.vecOfArray outDim bArr
        | throw <| IO.userError "layers.0.bias must be a float array of length 10"
      pure { weights := w, bias := b }
  | _ =>
      throw <| IO.userError "Weights JSON must be an object"

/-- Load the digits test dataset exported from Python (JSON). -/
def loadDataset (path : String) : IO (Array (Tensor Float xShape × Nat)) := do
  let j ← readJsonObjectFile path
  let examples ←
    match ← optionalField? j "examples" "dataset" with
    | none => pure #[]
    | some examplesJ => expectArray examplesJ "dataset.examples"
  let mut out : Array (Tensor Float xShape × Nat) := #[]
  for e in examples do
    let eo ← expectObject e "dataset example"
    let xJ ← expectField eo "x" "dataset example"
    let y ← expectFieldNat eo "y" "dataset example"
    let vec ← NN.Verification.Json.expectFiniteFloatArray xJ "dataset example.x"
    let some xT := NN.Verification.Util.Tensor.vecOfArray inDim vec
      | throw <| IO.userError "Dataset example 'x' must be a float array of length 64"
    out := out.push (xT, y)
  pure out

/-- Running counters for the digits certified-accuracy workflow. -/
structure Report where
  /-- Number of examples checked. -/
  total : Nat := 0
  /-- Number of clean examples classified correctly by the exported model. -/
  nominalOk : Nat := 0
  /-- Number of examples certified by interval bound propagation. -/
  ibpOk : Nat := 0
  /-- Number of examples certified by the affine CROWN pass. -/
  crownOk : Nat := 0
  deriving Repr

/--
Run the certified-accuracy evaluation once, under a chosen scalar backend `α`.

This lowers the linear classifier to the verifier IR, then checks each example's $L^\infty$ box
using IBP and a simple affine pass.
-/
def runOnce {α : Type} [TorchLean.Storage α] [Context α]
    [BoundOps α] [NonlinearBoundOps α] [ToString α]
    [TorchLean.Runtime.FromFloat α] (options : Options) : IO Report := do
  let cast : Float → α := TorchLean.Runtime.ofFloat
  let linF ← loadWeights options.weights
  let examples0 ← loadDataset options.dataset
  let examples := examples0.take options.max

  let params : TorchLean.nn.State α paramShapes :=
    TorchLean.nn.State.empty
      |>.push (TorchLean.Tensor.map cast linF.weights)
      |>.push (TorchLean.Tensor.map cast linF.bias)

  let lowered ←
    match TorchLean.Verification.lowerProgramToIR
          (α := α) (classifier (α := α)) params with
    | .ok c => pure c
    | .error e => throw <| IO.userError e

  IO.println s!"[digits] lowered IR nodes: {lowered.graph.nodes.size}"

  let eps : α := cast options.eps
  let rad : Tensor α xShape := Tensor.full (α := α) xShape eps
  let ctx : AffineCtx := { inputId := lowered.inputId, inputDim := inDim }

  let mut report : Report := {}

  for (xF, yNat) in examples do
    report := { report with total := report.total + 1 }

    let yF : Tensor Float yShape := Spec.linearSpec (α := Float) linF xF
    if (TorchLean.Metrics.argmax? (α := Float) yF).map Fin.val = some yNat then
      report := { report with nominalOk := report.nominalOk + 1 }

    let x0 : Tensor α xShape := TorchLean.Tensor.map cast xF
    let loX := Tensor.clampSpec (Tensor.subSpec x0 rad) (0 : α) 1
    let hiX := Tensor.clampSpec (Tensor.addSpec x0 rad) (0 : α) 1
    let xB : FlatBox α :=
      { dim := inDim, lo := loX, hi := hiX }

    let ps : ParamStore α := lowered.seedInputBox xB

    let ibp := lowered.runIBP ps
    let outB ← lowered.outputBoxOrThrow ibp
    if hOut : outB.dim = outDim then
      let loY : Tensor α yShape := by
        simpa [yShape] using outB.loAsDim hOut
      let hiY : Tensor α yShape := by
        simpa [yShape] using outB.hiAsDim hOut
      if TopLabel.certifiesLabelFromTensorBounds (α := α) loY hiY yNat then
        report := { report with ibpOk := report.ibpOk + 1 }
    else
      throw <| IO.userError s!"Unexpected output dim {outB.dim} (expected {outDim})"

    let affs := runAffine (α := α) lowered.graph ps ctx ibp
    match lowered.outputAffine? affs with
    | .error _ =>
        -- Should not happen for linear/relu/linear graphs.
        pure ()
    | .ok outAff =>
      if hIn : outAff.inDim = inDim then
        if hOut : outAff.outDim = outDim then
            let outC := outAff.evalOnFlatBoxAsDim xB hIn.symm hOut
            let loY : Tensor α yShape := by
              simpa [yShape] using outC.lo
            let hiY : Tensor α yShape := by
              simpa [yShape] using outC.hi
            if TopLabel.certifiesLabelFromTensorBounds (α := α) loY hiY yNat then
              report := { report with crownOk := report.crownOk + 1 }
          else
            pure ()
        else
          pure ()

  IO.println s!"[digits] examples={report.total} eps={options.eps}"
  IO.println s!"[digits] nominal accuracy: {report.nominalOk}/{report.total}"
  IO.println s!"[digits] certified (IBP):   {report.ibpOk}/{report.total}"
  IO.println s!"[digits] certified (CROWN): {report.crownOk}/{report.total}"
  pure report

/--
CLI entry point for the digits certified-robustness workflow.

This is wired into `lake exe verify -- digits`.
-/
def main (args : List String) : IO Unit := do
  IO.println "== TorchLean digits certified robustness =="
  let (arithmetic, rest) ←
    match TorchLean.Runtime.Arithmetic.parseAndStrip args with
    | .ok v => pure v
    | .error msg => throw <| IO.userError msg
  TorchLean.Runtime.Arithmetic.log arithmetic
  let options ←
    match parseArgs rest with
    | .ok o => pure o
    | .error msg => throw <| IO.userError msg
  NN.Verification.Builtin.withBoundArithmetic arithmetic
    (fun {α} _ _ _ _ _ _ => do
      let _ ← runOnce (α := α) options
      pure ())

/--
Train a fresh digits classifier, lower it through the TorchLean verifier path, and certify it.

The Python trainer is an artifact producer only. Lean still parses the exported JSON, lowers the
TorchLean program to verifier IR, runs IBP and affine CROWN bounds, and prints the certification
report from the checked artifacts.
-/
def mainTrainThenCertify (args : List String) : IO Unit := do
  IO.println "== TorchLean digits train → lower → certify =="
  let (arithmetic, rest) ←
    match TorchLean.Runtime.Arithmetic.parseAndStrip args with
    | .ok v => pure v
    | .error msg => throw <| IO.userError msg
  TorchLean.Runtime.Arithmetic.log arithmetic
  let options ←
    match parseTrainCertifyArgs rest with
    | .ok o => pure o
    | .error msg => throw <| IO.userError msg

  let pythonCmd ← TorchLean.External.Process.resolveCmdFromEnv "TORCHLEAN_PYTHON" "python3"
  let python ← TorchLean.External.Process.ensureCmdAvailable
    "Python 3" pythonCmd #["--version"] (some "TORCHLEAN_PYTHON")
  IO.println s!"[digits] training/export script: {options.script}"
  IO.println s!"[digits] exported weights: {options.certify.weights}"
  IO.println s!"[digits] exported dataset: {options.certify.dataset}"
  let out ← TorchLean.External.Process.runStdoutChecked
    (ctx := "digits train/export")
    (cmd := python)
    (args := trainerArgs options)
    (cwd := some ".")
  let trainLog := out.trimAscii.toString
  if !trainLog.isEmpty then
    IO.println trainLog
  IO.println "[digits] Python export complete; entering Lean certification path."

  NN.Verification.Builtin.withBoundArithmetic arithmetic
    (fun {α} _ _ _ _ _ _ => do
      let report ← runOnce (α := α) options.certify
      if report.total = 0 then
        throw <| IO.userError "digits train-then-certify produced an empty report"
      IO.println
        (s!"[digits] report: total={report.total}, nominal={report.nominalOk}, " ++
          s!"ibp={report.ibpOk}, crown={report.crownOk}"))

end NN.Verification.Robustness.Digits
