/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import NN.API.Verification.Lowering
public import NN.Core.ExternalProcess
public import NN.Verification.Robustness.TopLabel
public import NN.Verification.Util.Json
public import NN.Verification.Util.Tensor
public import NN.Runtime.Autograd.Model.Metrics

/-!
# Digits certified robustness

Certified accuracy for a linear classifier on sklearn's digits dataset.

Workflow:
- Train a small linear classifier on sklearn's digits (8x8) in Python and export:
  - weights JSON (`digits_linear_weights.json`)
  - test dataset JSON (`digits_test.json`)
- In Lean, load the weights + dataset and compute certified accuracy under an $\ell^\infty$ input
  box using:
  - IBP (`runIBP`)
  - CROWN (`outputBoxCROWN?`), which takes each lower endpoint from the lower affine form and each
    upper endpoint from the upper form

Run:
  `scripts/lake.sh exe verify -- digits`
  `scripts/lake.sh exe verify -- digits --eps=0.02 --max=360`
  `scripts/lake.sh exe verify -- digits --arithmetic ieee --eps=0.02`
  `scripts/lake.sh exe verify -- digits-train-certify --epochs=50 --eps=0.02 --max=100`

Regenerate assets:
  `python3 scripts/verification/robustness/train_digits_linear.py`
-/

@[expose] public section


namespace NN.Verification.Robustness.Digits

open Spec TorchLean

open NN.MLTheory.CROWN.Graph
open NN.MLTheory.CROWN
open Lean
open Json
open NN.Verification.Json

/-- Bundled sklearn-digits linear classifier weights. -/
def defaultWeightsPath : String :=
  "NN/Examples/Verification/Robustness/digits_linear_weights.json"

/-- Bundled sklearn-digits test set. -/
def defaultDatasetPath : String :=
  "NN/Examples/Verification/Robustness/digits_test.json"

/-- Python exporter used by the train-then-certify command. -/
def defaultTrainScript : String :=
  "scripts/verification/robustness/train_digits_linear.py"

/-- CLI options for the digits certified-accuracy workflow. -/
structure Options where
  /-- Weights JSON path (PyTorch export). -/
  weights : String := defaultWeightsPath
  /-- Dataset JSON path (PyTorch export). -/
  dataset : String := defaultDatasetPath
  /-- $L^\infty$ perturbation radius around each input example. -/
  eps     : Float  := 0.02
  /-- Max number of examples to evaluate (for local checks). -/
  max     : Nat    := 100
  deriving Repr

/-- Options for the train → lower → certify report command. -/
structure Training.Options where
  /-- Lean side certification options after Python exports the model and dataset. -/
  certify : NN.Verification.Robustness.Digits.Options := {}
  /-- Python trainer script path. -/
  script : String := defaultTrainScript
  /-- Reproducibility seed forwarded to the trainer. -/
  seed : Nat := 0
  /-- Number of Python training epochs. -/
  epochs : Nat := 200
  /-- Python trainer batch size. -/
  batch : Nat := 128
  /-- Python trainer learning rate. -/
  lr : Float := 1e-2
  /-- Test split fraction used by the trainer. -/
  testSize : Float := 0.2
  /-- Number of test examples exported by the trainer. -/
  maxTest : Nat := 360
  deriving Repr

/-- Usage string printed on `--help` / `-h`. -/
def usage : String :=
  String.intercalate "\n" [
    "Usage:",
    ("  scripts/lake.sh exe verify -- digits [--weights=PATH.json] " ++
      "[--dataset=PATH.json] [--eps=0.02] [--max=100]"),
    ("  scripts/lake.sh exe verify -- digits-train-certify [trainer flags] " ++
      "[--weights=PATH.json] [--dataset=PATH.json] [--eps=0.02] [--max=100]"),
    "",
    "Notes:",
    "  - Arithmetic flags are also accepted (e.g. --arithmetic ieee).",
    "  - digits-train-certify runs the Python trainer, then lowers and certifies in Lean.",
    s!"  - Assets are generated by: python3 {defaultTrainScript}"
  ]

/--
Consume the certification flags shared by both digits commands (after `--` stripping and the
`--help` check), returning the remaining arguments. Flags are extracted by key, so the caller may
consume its own flags from the remainder in any order.
-/
def Options.parseRest (args : List String) : Except String (Options × List String) := do
  let defaults : Options := {}
  let args := TorchLean.CLI.dropDashDash args
  if TorchLean.CLI.hasHelp args then
    throw usage
  let (weights, args) ← CLI.takeFlagValue args "weights" (default := defaults.weights)
  let (dataset, args) ← CLI.takeFlagValue args "dataset" (default := defaults.dataset)
  let (eps, args) ← CLI.takeFloatFlag args "eps" (default := defaults.eps)
  -- Empty or unordered perturbation boxes must not certify vacuously.
  unless eps ≥ 0 && eps.isFinite do
    throw s!"--eps must be a finite nonnegative radius, got {eps}"
  let (max, args) ← CLI.takeNatFlag args "max" (default := defaults.max)
  pure ({ weights := weights, dataset := dataset, eps := eps, max := max }, args)

/-- Parse CLI args into `Options` (returns `usage` as the error message on `--help`). -/
def Options.parse (args : List String) : Except String Options := do
  let (options, args) ← Options.parseRest args
  TorchLean.CLI.checkNoArgs args
  pure options

/-- Parse the combined trainer/certifier CLI for `digits-train-certify`. -/
def Training.parse (args : List String) : Except String Training.Options := do
  let defaults : Training.Options := {}
  let (certify, args) ← Options.parseRest args
  let (script, args) ← CLI.takeFlagValue args "script" (default := defaults.script)
  let (seed, args) ← CLI.takeNatFlag args "seed" (default := defaults.seed)
  let (epochs, args) ← CLI.takeNatFlag args "epochs" (default := defaults.epochs)
  let (batch, args) ← CLI.takeNatFlag args "batch" (default := defaults.batch)
  let (lr, args) ← CLI.takeFloatFlag args "lr" (default := defaults.lr)
  let (testSize, args) ← CLI.takeFloatFlag args "test-size" (default := defaults.testSize)
  let (maxTest, args) ← CLI.takeNatFlag args "max-test" (default := defaults.maxTest)
  TorchLean.CLI.checkNoArgs args
  pure {
    certify := certify
    script := script
    seed := seed
    epochs := epochs
    batch := batch
    lr := lr
    testSize := testSize
    maxTest := maxTest
  }

/-- Python trainer arguments, including the artifact destinations checked by Lean afterward. -/
def Training.args (options : Training.Options) : Array String :=
  #[
    options.script,
    "--seed", toString options.seed,
    "--epochs", toString options.epochs,
    "--lr", toString options.lr,
    "--batch", toString options.batch,
    "--test-size", toString options.testSize,
    "--max-test", toString options.maxTest,
    "--out-weights", options.certify.weights,
    "--out-dataset", options.certify.dataset
  ]

/-- Load linear classifier weights exported from PyTorch into a typed `LinearSpec`. -/
def loadWeights (path : String) : IO (Spec.LinearSpec Float 64 10) := do
  let j ← readJsonObjectFile path
  let wJ ← expectField j "layers.0.weight" "weights"
  let bJ ← expectField j "layers.0.bias" "weights"
  let wArr ← expectFiniteFloatMatrix wJ "layers.0.weight"
  let bArr ← expectFiniteFloatArray bJ "layers.0.bias"
  let some w := NN.Verification.Util.Tensor.ofRows? 10 64 wArr
    | throw <| IO.userError
        "layers.0.weight must be a float matrix of shape [10][64]"
  let b ← NN.Verification.Util.Tensor.requireArray "layers.0.bias" [10] bArr
  pure { weights := w, bias := b }

/-- Load the digits test dataset exported from Python (JSON). -/
def loadDataset (path : String) : IO (Array (Tensor Float [64] × Nat)) := do
  let j ← readJsonObjectFile path
  let examples ←
    match ← optionalField? j "examples" "dataset" with
    | none => pure #[]
    | some examplesJ => expectArray examplesJ "dataset.examples"
  let mut out : Array (Tensor Float [64] × Nat) := #[]
  for e in examples do
    let eo ← expectObject e "dataset example"
    let xJ ← expectField eo "x" "dataset example"
    let y ← expectFieldNat eo "y" "dataset example"
    let vec ← expectFiniteFloatArray xJ "dataset example.x"
    let xT ← NN.Verification.Util.Tensor.requireArray "dataset example.x" [64] vec
    out := out.push (xT, y)
  pure out

/-- Running counters for the digits certified-accuracy workflow. -/
structure Report where
  /-- Number of examples checked. -/
  total : Nat := 0
  /-- Number of clean examples classified correctly by the exported model. -/
  nominalOk : Nat := 0
  /-- Number of examples certified by interval bound propagation. -/
  ibpOk : Nat := 0
  /-- Number of examples certified by the affine CROWN pass. -/
  crownOk : Nat := 0
  deriving Repr

/--
The certified input box: the binary64 `ℓ∞` ball around `x`, rounded outward by `FlatBox.lInfBall`,
clipped to the pixel range `[0, 1]`, and converted to `α` with the directed rounding of
`TorchLean.Runtime.ofFloatDirected`. It contains every real input within `eps` of the binary64
center that lies in `[0, 1]`.
-/
def inputBox {α : Type} [Storage α] [Context α] [Runtime.FromFloat α] {shape : Shape}
    (x : Tensor Float shape) (eps : Float) : FlatBox α :=
  let ball := FlatBox.lInfBall (α := Float) x eps
  let clip (v : Float) : Float := min 1 (max 0 v)
  { dim := ball.dim
    lo := TorchLean.Tensor.map
      (fun v => TorchLean.Runtime.ofFloatDirected (α := α) false (clip v)) ball.lo
    hi := TorchLean.Tensor.map
      (fun v => TorchLean.Runtime.ofFloatDirected (α := α) true (clip v)) ball.hi }

/--
Run the certified-accuracy evaluation once, under a chosen scalar backend `α`.

This lowers the linear classifier to the verifier IR, then checks each example's $L^\infty$ box
using IBP and two-sided CROWN output bounds.
-/
def run {α : Type} [Storage α] [Context α]
    [BoundOps α] [NonlinearBoundOps α] [ToString α]
    [TorchLean.Runtime.FromFloat α] (options : Options) : IO Report := do
  let cast : Float → α := TorchLean.Runtime.ofFloat
  let linF ← loadWeights options.weights
  let examples0 ← loadDataset options.dataset
  let examples := examples0.take options.max

  let params : nn.State α [[10, 64], [10]] :=
    TorchLean.nn.State.empty
      |>.push (TorchLean.Tensor.map cast linF.weights)
      |>.push (TorchLean.Tensor.map cast linF.bias)

  let model : Runtime.Program α [[10, 64], [10], [64]] [10] :=
    fun {m} _ _ w b x =>
      Runtime.linear (m := m) (α := α)
        (batchShape := []) (inputWidth := 64) (outputWidth := 10) w b x
  let lowered ← IO.ofExcept <|
    Verification.lowerProgramToIR (α := α) model params

  IO.println s!"[digits] lowered IR nodes: {lowered.graph.nodes.size}"

  let mut report : Report := {}

  for (xF, yNat) in examples do
    report := { report with total := report.total + 1 }

    let yF : Tensor Float [10] := Spec.linearSpec (α := Float) linF xF
    if (TorchLean.Metrics.argmax? (α := Float) yF).map Fin.val = some yNat then
      report := { report with nominalOk := report.nominalOk + 1 }

    let xB : FlatBox α := inputBox xF options.eps

    let ps : ParamStore α := lowered.seedInputBox xB

    let ibp := lowered.runIBP ps
    let outB ← IO.ofExcept (lowered.outputBox? ibp)
    if hOut : outB.dim = 10 then
      let loY : Tensor α [10] := outB.loAsDim hOut
      let hiY : Tensor α [10] := outB.hiAsDim hOut
      if TopLabel.check loY hiY yNat then
        report := { report with ibpOk := report.ibpOk + 1 }
    else
      throw <| IO.userError s!"Unexpected output dim {outB.dim} (expected 10)"

    -- CROWN returns separate lower and upper affine bounds; taking both endpoints from the
    -- upper form alone can certify a class that actually loses somewhere in the input box.
    match outputBoxCROWN? lowered.graph ps xB lowered.inputId lowered.outputId xB.dim with
    | .ok bounds =>
      if TopLabel.check bounds.lo bounds.hi yNat then
        report := { report with crownOk := report.crownOk + 1 }
    | .error e => throw <| IO.userError s!"CROWN failed: {e}"

  IO.println s!"[digits] examples={report.total} eps={options.eps}"
  IO.println s!"[digits] nominal accuracy: {report.nominalOk}/{report.total}"
  IO.println s!"[digits] certified (IBP):   {report.ibpOk}/{report.total}"
  IO.println s!"[digits] certified (CROWN): {report.crownOk}/{report.total}"
  pure report

/--
CLI entry point for the digits certified-robustness workflow.

This is wired into `scripts/lake.sh exe verify -- digits`.
-/
def main (args : List String) : IO Unit := do
  IO.println "== TorchLean digits certified robustness =="
  let (arithmetic, rest) ← IO.ofExcept (TorchLean.Runtime.Arithmetic.parseAndStrip args)
  TorchLean.Runtime.Arithmetic.log arithmetic
  let options ← IO.ofExcept (Options.parse rest)
  NN.Verification.Builtin.withBoundArithmetic arithmetic
    (fun {α} _ _ _ _ _ _ => do
      let _ ← run (α := α) options
      pure ())

/--
Train a fresh digits classifier, lower it through the TorchLean verifier path, and certify it.

The Python trainer is an artifact producer only. Lean still parses the exported JSON, lowers the
TorchLean program to verifier IR, runs IBP and affine CROWN bounds, and prints the certification
report from the checked artifacts.
-/
def Training.main (args : List String) : IO Unit := do
  IO.println "== TorchLean digits train → lower → certify =="
  let (arithmetic, rest) ← IO.ofExcept (TorchLean.Runtime.Arithmetic.parseAndStrip args)
  TorchLean.Runtime.Arithmetic.log arithmetic
  let options ← IO.ofExcept (Training.parse rest)

  let pythonCmd ← TorchLean.External.Process.command "TORCHLEAN_PYTHON" "python3"
  let python ← TorchLean.External.Process.require
    "Python 3" pythonCmd #["--version"] (some "TORCHLEAN_PYTHON")
  IO.println s!"[digits] training/export script: {options.script}"
  IO.println s!"[digits] exported weights: {options.certify.weights}"
  IO.println s!"[digits] exported dataset: {options.certify.dataset}"
  let out ← TorchLean.External.Process.run
    (ctx := "digits train/export")
    (cmd := python)
    (args := Training.args options)
    (cwd := some ".")
  let trainLog := out.trimAscii.toString
  if !trainLog.isEmpty then
    IO.println trainLog
  IO.println "[digits] Python export complete; entering Lean certification path."

  NN.Verification.Builtin.withBoundArithmetic arithmetic
    (fun {α} _ _ _ _ _ _ => do
      let report ← run (α := α) options.certify
      if report.total = 0 then
        throw <| IO.userError "digits train-then-certify produced an empty report"
      IO.println
        (s!"[digits] report: total={report.total}, nominal={report.nominalOk}, " ++
          s!"ibp={report.ibpOk}, crown={report.crownOk}"))

end NN.Verification.Robustness.Digits
