/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import NN.Verification.Robustness.MarginCert

/-!
# Bundled logit-bound report CLI

Command entry point for checking the bundled logit-bound report. The JSON checker lives
in `NN.Verification.Robustness.MarginCert`; this module supplies the repository default artifact
path used by `lake exe verify -- margin-report`.
-/

@[expose] public section

namespace NN.Verification.Robustness.MarginCertCLI

/-- Bundled report generated by the robustness export script. -/
def defaultPath : String :=
  "NN/Examples/Verification/Robustness/digits_linear_margin_cert.json"

/-- CLI entry point for `lake exe verify -- margin-report [report.json]`. -/
def run (args : List String) : IO Unit := do
  let usage :=
    String.intercalate "\n" [
      "Usage:",
      "  lake exe verify -- margin-report [<path/to/report.json>]",
      "",
      "If no path is provided, uses the bundled digits report:",
      s!"  {defaultPath}",
      "",
      "To regenerate the report:",
      "  python3 scripts/verification/robustness/export_margin_cert.py"
    ]

  if TorchLean.CLI.hasHelp args then
    IO.println usage
    return

  NN.Verification.Robustness.MarginCert.runWithDefault defaultPath args

end NN.Verification.Robustness.MarginCertCLI
