/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import NN.Spec.Dynamics.System
public import NN.Spec.Layers.SelectiveScan

/-!
# State-space dynamical systems

State-space sequence models are recurrent dynamical systems:

$$
h_{t+1}=A_t h_t+B_t x_t,\qquad
y_t=C_t h_t+D_t x_t.
$$

The full S4/Mamba family uses structured matrices and input-dependent ("selective") parameters.
This file starts with the diagonal/channelwise version because it is:

- the primitive implemented by a compact CUDA selective-scan kernel,
- enough to express the formal affine-scan algebra,
- and a useful educational baseline for examples.

The definitions reuse `DynamicalSystem` / `DrivenSystem` from
`NN/Spec/Dynamics/System.lean`, so existing notions such as `iterate`, `trajectory`,
`IsFixedPoint`, and `isContractive` apply immediately.
-/

@[expose] public section


namespace Spec.Dynamics
open TorchLean

open _root_.Spec _root_.TorchLean

/--
A diagonal state-space model with elementwise input, state, and output channels.

This is the smallest useful SSM shape: it captures the recurrent memory path used by Mamba/S4 while
remaining easy to verify.  Richer models can wrap this core with linear projections and gates.
-/
structure DiagonalSSM (α : Type) [TorchLean.Storage α] (dim : Nat) where
  /-- Elementwise recurrent multiplier. Stability usually requires $\lvert A_i\rvert<1$. -/
  A : Tensor α [dim]
  /-- Elementwise input-to-state gain. -/
  B : Tensor α [dim]
  /-- Elementwise state-to-output gain. -/
  C : Tensor α [dim]
  /-- Elementwise residual / skip gain. -/
  D : Tensor α [dim]

namespace DiagonalSSM

variable {α : Type} [TorchLean.Storage α] [Add α] [Mul α] {dim : Nat}

/-- One recurrent state update $h'=A\odot h+B\odot x$. -/
def step (m : DiagonalSSM α dim)
    (h x : Tensor α [dim]) : Tensor α [dim] :=
  Tensor.addSpec (Tensor.mulSpec m.A h) (Tensor.mulSpec m.B x)

/-- Readout $y=C\odot h+D\odot x$. -/
def readout (m : DiagonalSSM α dim)
    (h x : Tensor α [dim]) : Tensor α [dim] :=
  Tensor.addSpec (Tensor.mulSpec m.C h) (Tensor.mulSpec m.D x)

/-- Convert a token vector into the corresponding affine transition for the hidden state. -/
def transition (m : DiagonalSSM α dim)
    (x : Tensor α [dim]) : DiagonalTransition α dim :=
  { a := m.A, b := Tensor.mulSpec m.B x }

/-- Applying the affine transition generated by `x` is exactly the SSM state update. -/
@[simp] theorem transition_apply_eq_step (m : DiagonalSSM α dim)
    (h x : Tensor α [dim]) :
    (m.transition x).apply h = m.step h x := by
  simp [transition, DiagonalTransition.apply, step]

/-- Run a full input sequence and return all hidden states. -/
def scan (m : DiagonalSSM α dim)
    (h0 : Tensor α [dim])
    (xs : Array (Tensor α [dim])) :
    Array (Tensor α [dim]) :=
  diagonalSelectiveScan h0 (xs.map (fun x => m.transition x))

/-- Scanning no input produces no hidden states. -/
@[simp] theorem scan_nil (m : DiagonalSSM α dim)
    (h0 : Tensor α [dim]) :
    m.scan h0 #[] = #[] := by
  simp [scan, diagonalSelectiveScan]

/-- A diagonal SSM scan returns one hidden state for each input token. -/
@[simp] theorem scan_size (m : DiagonalSSM α dim)
    (h0 : Tensor α [dim])
    (xs : Array (Tensor α [dim])) :
    (m.scan h0 xs).size = xs.size := by
  unfold scan
  rw [diagonalSelectiveScan_size, Array.size_map]

end DiagonalSSM

/--
View a scalar-specialized diagonal SSM recurrence as a `DrivenSystem`.

`DrivenSystem` uses TorchLean's default `SpecScalar`, while the reusable SSM record
above is polymorphic over scalar backends.  This adapter is the bridge to the existing dynamics API.
-/
def DiagonalSSM.drivenSystemSpecScalar {dim : Nat}
    (m : DiagonalSSM SpecScalar dim) : DrivenSystem (.dim dim .scalar) (.dim dim .scalar) where
  step := fun h x => m.step h x

/-- Viewing a diagonal SSM as a driven dynamical system does not change its step.

The wrapper exists so the dynamics theorems apply to the layer; this is the `rfl` that says the
wrapper carries no extra content, so a bound proved about the system holds of the layer. -/
@[simp] theorem DiagonalSSM.drivenSystemSpecScalar_step {dim : Nat}
    (m : DiagonalSSM SpecScalar dim)
    (h x : Tensor SpecScalar [dim]) :
    (m.drivenSystemSpecScalar).step h x = m.step h x := by
  rfl

end Spec.Dynamics
