/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import NN.Spec.Core.Scalar
public import NN.Spec.Core.TensorOps

/-!
# System

Spec-level dynamical systems.

Global dynamics are properties of the spec transition function, independent of
runtime encodings or execution order.

## Why this layer exists (global dynamics context)

The paper "Formalized Hopfield Networks and Boltzmann Machines"
(Cipollina--Karatarakis--Wiedijk, 2025, arXiv:2512.07766) is a useful reference point for the kind
of global dynamical claims this layer is meant to support.  That paper includes deterministic
Hopfield convergence, Hebbian-learning, and stochastic Boltzmann/Perron--Frobenius developments.

This repository uses the layer for checked Hopfield trajectory facts and reusable
transition-system interfaces. The checked results cover
the deterministic asynchronous Hopfield trajectory facts under
`NN.MLTheory.Proofs.Hopfield`, while this file provides reusable transition-system interfaces and
trajectory lemmas for other models.  We do not claim the Boltzmann, Hebbian, ergodicity, or
Perron--Frobenius parts are implemented here.

All of these topics concern *trajectories* generated by repeatedly applying an update rule,
independently of any runtime implementation. This file therefore abstracts the core notion down to
`step : SpecTensor s → SpecTensor s`.

This file provides two complementary layers:

- executable semantics (`iterate`, `trajectory`, `iterateWithInput`, and adapters such as
  `DrivenSystem.freeze`), and
- proof interfaces (`IsFixedPoint`, contraction, Lyapunov stability).

The predicates remain propositions because stability is a mathematical claim, but the file should
not stop at predicates.  It also proves the algebra of discrete trajectories, so SSMs, diffusion
samplers, Hopfield systems, and ODE discretizations can reuse the same recurrence lemmas instead of
re-proving bookkeeping facts locally.
-/

@[expose] public section


namespace Spec.Dynamics

open _root_.Spec _root_.TorchLean

/-- Discrete-time dynamical system on spec tensors. -/
structure DynamicalSystem (s : Shape) where
  /-- One autonomous transition of the system state. -/
  step : SpecTensor s → SpecTensor s

/-- Driven system with exogenous input. -/
structure DrivenSystem (s u : Shape) where
  /-- One transition of the system state, parameterized by the current external input. -/
  step : SpecTensor s → SpecTensor u → SpecTensor s

/-- Iteration semantics for a discrete-time system. -/
def iterate {s : Shape} (sys : DynamicalSystem s) (n : Nat) (x : SpecTensor s) : SpecTensor s :=
  Nat.iterate sys.step n x

/-- Zero iterations leave the initial state unchanged. -/
@[simp] theorem iterate_zero {s : Shape} (sys : DynamicalSystem s) (x : SpecTensor s) :
    iterate sys 0 x = x := by
  rfl

/-- One more iteration applies one system step after the previous trajectory state. -/
@[simp] theorem iterate_succ {s : Shape} (sys : DynamicalSystem s) (n : Nat)
    (x : SpecTensor s) :
    iterate sys (n + 1) x = sys.step (iterate sys n x) := by
  dsimp [iterate]
  induction n generalizing x with
  | zero => rfl
  | succ n ih =>
      simp only [Function.iterate_succ_apply, ih]

/-- Running `m+n` steps is the same as running `n` steps and then `m` more. -/
theorem iterate_add {s : Shape} (sys : DynamicalSystem s) (m n : Nat) (x : SpecTensor s) :
    iterate sys (m + n) x = iterate sys m (iterate sys n x) := by
  dsimp [iterate]
  rw [Function.iterate_add_apply]

/-- The trajectory (orbit) of an initial condition under `sys`. -/
def trajectory {s : Shape} (sys : DynamicalSystem s) (x0 : SpecTensor s) : Nat → SpecTensor s :=
  fun t => iterate sys t x0

/-- The first point of a trajectory is its initial condition. -/
@[simp] theorem trajectory_zero {s : Shape} (sys : DynamicalSystem s) (x0 : SpecTensor s) :
    trajectory sys x0 0 = x0 := by
  rfl

/-- Successive trajectory points are related by the system transition. -/
@[simp] theorem trajectory_succ {s : Shape} (sys : DynamicalSystem s) (x0 : SpecTensor s)
    (n : Nat) :
    trajectory sys x0 (n + 1) = sys.step (trajectory sys x0 n) := by
  simp [trajectory]

/-- Iteration semantics for a driven system with an input stream. -/
def iterateWithInput {s u : Shape} (sys : DrivenSystem s u) (inputSeq : Nat → SpecTensor u) :
    Nat → SpecTensor s → SpecTensor s
  | 0, x => x
  | n + 1, x => sys.step (iterateWithInput sys inputSeq n x) (inputSeq n)

/-- The trajectory (orbit) of a driven system under a fixed input stream. -/
def drivenTrajectory {s u : Shape} (sys : DrivenSystem s u)
    (inputSeq : Nat → SpecTensor u) (x0 : SpecTensor s) : Nat → SpecTensor s :=
  fun t => iterateWithInput sys inputSeq t x0

/-- Zero driven steps leave the initial state unchanged. -/
@[simp] theorem iterateWithInput_zero {s u : Shape} (sys : DrivenSystem s u)
    (inputSeq : Nat → SpecTensor u) (x : SpecTensor s) :
    iterateWithInput sys inputSeq 0 x = x := by
  rfl

/-- The first point of a driven trajectory is its initial condition. -/
@[simp] theorem drivenTrajectory_zero {s u : Shape} (sys : DrivenSystem s u)
    (inputSeq : Nat → SpecTensor u) (x0 : SpecTensor s) :
    drivenTrajectory sys inputSeq x0 0 = x0 := by
  rfl

/-- A driven trajectory advances by applying the next input to the previous driven state. -/
@[simp] theorem iterateWithInput_succ {s u : Shape} (sys : DrivenSystem s u)
    (inputSeq : Nat → SpecTensor u) (n : Nat) (x : SpecTensor s) :
    iterateWithInput sys inputSeq (n + 1) x =
      sys.step (iterateWithInput sys inputSeq n x) (inputSeq n) := by
  rfl

/-- Successive driven trajectory points follow the driven transition and input stream. -/
@[simp] theorem drivenTrajectory_succ {s u : Shape} (sys : DrivenSystem s u)
    (inputSeq : Nat → SpecTensor u) (x0 : SpecTensor s) (n : Nat) :
    drivenTrajectory sys inputSeq x0 (n + 1) =
      sys.step (drivenTrajectory sys inputSeq x0 n) (inputSeq n) := by
  rfl

/-- Freeze a driven system at a fixed input, turning it into an autonomous system. -/
def DrivenSystem.freeze {s u : Shape} (sys : DrivenSystem s u)
    (input : SpecTensor u) : DynamicalSystem s where
  step := fun x => sys.step x input

/-- A frozen driven system takes the same step as the original system at the frozen input. -/
@[simp] theorem DrivenSystem.freeze_step {s u : Shape} (sys : DrivenSystem s u)
    (input : SpecTensor u) (x : SpecTensor s) :
    (sys.freeze input).step x = sys.step x input := by
  rfl

/-- Constant-input driven iteration agrees with iteration of the frozen autonomous system. -/
theorem iterateWithInput_const_eq_iterate {s u : Shape} (sys : DrivenSystem s u)
    (input : SpecTensor u) (n : Nat) (x : SpecTensor s) :
    iterateWithInput sys (fun _ => input) n x =
      iterate (sys.freeze input) n x := by
  induction n generalizing x with
  | zero =>
      rfl
  | succ n ih =>
      simp [iterateWithInput, iterate_succ, DrivenSystem.freeze, ih]

/-- Constant-input driven trajectories agree with trajectories of the frozen autonomous system. -/
theorem drivenTrajectory_const_eq_trajectory {s u : Shape} (sys : DrivenSystem s u)
    (input : SpecTensor u) (x0 : SpecTensor s) (n : Nat) :
    drivenTrajectory sys (fun _ => input) x0 n =
      trajectory (sys.freeze input) x0 n := by
  exact iterateWithInput_const_eq_iterate sys input n x0

/-- `x` is a fixed point (equilibrium) of `sys` if `step x = x`. -/
def IsFixedPoint {s : Shape} (sys : DynamicalSystem s) (x : SpecTensor s) : Prop :=
  sys.step x = x

/-- A proof-carrying fixed-point witness. -/
structure FixedPointCertificate {s : Shape} (sys : DynamicalSystem s) where
  /-- Candidate equilibrium. -/
  point : SpecTensor s
  /-- Machine-checked proof that the candidate is a fixed point. -/
  isFixed : IsFixedPoint sys point

/-- Fixed points remain fixed under any number of iterations. -/
theorem fixedPoint_iterate {s : Shape} {sys : DynamicalSystem s} {x : SpecTensor s}
    (h : IsFixedPoint sys x) (n : Nat) :
    iterate sys n x = x := by
  induction n with
  | zero =>
      rfl
  | succ n ih =>
      rw [iterate_succ, ih, h]

/-- A trajectory initialized at a fixed point is constant. -/
theorem fixedPoint_trajectory {s : Shape} {sys : DynamicalSystem s} {x : SpecTensor s}
    (h : IsFixedPoint sys x) (n : Nat) :
    trajectory sys x n = x := by
  exact fixedPoint_iterate h n

/-- Distance between two states induced by a norm on spec tensors. -/
def distance {s : Shape}
    (norm : ∀ {s : Shape}, SpecTensor s → SpecScalar)
    (x y : SpecTensor s) : SpecScalar :=
  norm (TorchLean.Tensor.subSpec x y)

/-- Contraction property for spec dynamics. -/
def isContractive {s : Shape}
    (sys : DynamicalSystem s)
    (norm : ∀ {s : Shape}, SpecTensor s → SpecScalar)
    (factor : SpecScalar) : Prop :=
  factor < 1 ∧ ∀ x y, distance norm (sys.step x) (sys.step y) ≤ factor * distance norm x y

/--
Lyapunov stability of an equilibrium: every sufficiently small initial perturbation remains small
along the entire discrete trajectory.
-/
def isLyapunovStable {s : Shape}
    (sys : DynamicalSystem s)
    (norm : ∀ {s : Shape}, SpecTensor s → SpecScalar)
    (equilibrium : SpecTensor s) : Prop :=
  ∀ ε > 0, ∃ δ > 0, ∀ x₀,
    distance norm equilibrium x₀ < δ →
    ∀ n, distance norm equilibrium (iterate sys n x₀) < ε

/-- Lyapunov stability together with local convergence to the equilibrium. -/
def isAsymptoticallyStable {s : Shape}
    (sys : DynamicalSystem s)
    (norm : ∀ {s : Shape}, SpecTensor s → SpecScalar)
    (equilibrium : SpecTensor s) : Prop :=
  isLyapunovStable sys norm equilibrium ∧
  ∃ δ > 0, ∀ x₀,
    distance norm equilibrium x₀ < δ →
    ∀ ε > 0, ∃ N, ∀ n ≥ N, distance norm equilibrium (iterate sys n x₀) < ε

/-- Every initial condition converges to the equilibrium. -/
def isGloballyStable {s : Shape}
    (sys : DynamicalSystem s)
    (norm : ∀ {s : Shape}, SpecTensor s → SpecScalar)
    (equilibrium : SpecTensor s) : Prop :=
  ∀ x₀, ∀ ε > 0, ∃ N, ∀ n ≥ N,
    distance norm equilibrium (iterate sys n x₀) < ε

end Spec.Dynamics
