/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import Mathlib.Topology.ContinuousMap.StoneWeierstrass
public import NN.Proofs.Tensor.Euclidean
public import NN.Spec.Core.Tensor -- shake: keep

/-!
# Stone–Weierstrass Approximation for Tensor Inputs

This file does **not** prove the classical *neural network* universal approximation theorem
(Cybenko/Hornik/Leshno, etc.). That result is substantially more work to mechanize.

What we *do* prove here is a standard expressivity theorem in approximation theory:

> On any compact set $K\subseteq\mathbb{R}^n$, the subalgebra of continuous functions generated by
> the coordinate projections is dense in $C(K,\mathbb{R})$.

Equivalently: functions on a compact set can be uniformly approximated by polynomial expressions in
the coordinates (Stone–Weierstrass).

We phrase this for TorchLean’s rank-one tensors `Tensor ℝ [n]` with their Euclidean topology, using
the equivalence `Tensor.vectorEquiv` as a homeomorphism onto the standard product topology.

This module is therefore a topology/approximation bridge, not a claim about one particular neural
architecture.  The cited classical lineage is Stone--Weierstrass for polynomial density, with the
neural-network universal-approximation motivation coming from Cybenko, Hornik, Leshno et al., and
Pinkus. The ReLU compact-set file uses this bridge as one ingredient when relating
tensor-valued inputs to TorchLean network semantics.
-/

@[expose] public section


namespace NN.MLTheory.Proofs.UniversalApproximation

open Spec TorchLean
open TorchLean.Tensor
open scoped Topology

namespace VectorTensor

/-!
The topology on `Tensor ℝ [n]` is the Euclidean metric topology from `NN.Proofs.Tensor.Euclidean`.
The coordinate view `Tensor.vectorEquiv` is a linear equivalence between finite-dimensional real
normed spaces, hence a homeomorphism; no separate induced topology is installed here.
-/

/-- The tensor-to-function direction is continuous for the Euclidean topology. -/
theorem continuous_toFun (n : Nat) :
    Continuous (Tensor.vectorEquiv (α := ℝ) n).toFun :=
  Tensor.continuous_vectorEquiv n

/-- The function-to-tensor inverse is continuous, so the tensor/vector equivalence is a
homeomorphism. -/
theorem continuous_invFun (n : Nat) :
    Continuous (Tensor.vectorEquiv (α := ℝ) n).invFun :=
  Tensor.continuous_vectorEquiv_symm n

/-- Homeomorphism between rank-one tensors and coordinate functions
$\operatorname{Fin}(n)\to\mathbb{R}$. -/
noncomputable def homeomorph (n : Nat) : Tensor ℝ [n] ≃ₜ (Fin n → ℝ) where
  toEquiv := Tensor.vectorEquiv (α := ℝ) n
  continuous_toFun := continuous_toFun n
  continuous_invFun := continuous_invFun n

end VectorTensor

namespace StoneWeierstrass

open ContinuousMap

variable {n : Nat} (K : Set (Tensor ℝ [n]))

/-- Coordinate projection as a continuous map $K\to\mathbb{R}$. -/
noncomputable def coord (i : Fin n) : C(K, ℝ) :=
  ⟨fun x => ((Tensor.vectorEquiv (α := ℝ) n).toFun x.1) i,
    (continuous_apply i).comp
      ((VectorTensor.continuous_toFun n).comp continuous_subtype_val)⟩

/-- Subalgebra generated by the coordinate projections on the compact tensor domain `K`. -/
noncomputable def coordSubalg : Subalgebra ℝ C(K, ℝ) :=
  Algebra.adjoin ℝ (Set.range (coord (K := K)))

/--
Coordinate functions separate points.

If two tensor points differ, the tensor/vector equivalence gives a coordinate where they differ,
and that coordinate projection belongs to `coordSubalg`.
-/
theorem coordSubalg_separatesPoints : (coordSubalg (K := K)).SeparatesPoints := by
  classical
  intro x y hxy
  -- Reduce `x ≠ y` to a coordinate witness.
  have hfun :
      (Tensor.vectorEquiv (α := ℝ) n).toFun x.1 ≠ (Tensor.vectorEquiv (α := ℝ) n).toFun y.1 :=
        by
    intro h
    apply hxy
    apply Subtype.ext
    exact (Tensor.vectorEquiv (α := ℝ) n).injective h
  have hnot : ¬ ∀ i : Fin n,
      ((Tensor.vectorEquiv (α := ℝ) n).toFun x.1) i =
      ((Tensor.vectorEquiv (α := ℝ) n).toFun y.1) i := by
    intro hall
    apply hfun
    funext i
    exact hall i
  obtain ⟨i, hi⟩ := not_forall.mp hnot

  -- Use the `i`-th coordinate projection, viewed as a plain function `K → ℝ`.
  refine ⟨(fun z : K => ((Tensor.vectorEquiv (α := ℝ) n).toFun z.1) i), ?_, ?_⟩
  · -- Show this function comes from an element of the subalgebra.
    refine ⟨coord (K := K) i, ?_, rfl⟩
    refine Algebra.subset_adjoin (R := ℝ) (A := C(K, ℝ)) ?_
    exact ⟨i, rfl⟩
  · -- And it separates the points.
    -- `hi : ¬ ((...) x) = ((...) y)`
    simpa using hi

/--
Stone--Weierstrass closure theorem for the coordinate-generated subalgebra.

On a compact set, a subalgebra of continuous real-valued functions that separates points has dense
topological closure.  Here the coordinate projections provide the separation witness.
-/
theorem coordSubalg_topologicalClosure_eq_top [CompactSpace K] :
    (coordSubalg (K := K)).topologicalClosure = ⊤ :=
  ContinuousMap.subalgebra_topologicalClosure_eq_top_of_separatesPoints
    (A := coordSubalg (K := K)) (coordSubalg_separatesPoints (K := K))

/--
Approximate any continuous scalar function on $K$ by an element of the coordinate-generated
subalgebra.

This is the operational form used downstream: given $\varepsilon>0$, produce a
coordinate-polynomial-like continuous function within $\varepsilon$ in the supremum norm.
-/
theorem exists_coordSubalg_near_continuousMap
    [CompactSpace K] (f : C(K, ℝ)) (ε : ℝ) (hε : 0 < ε) :
    ∃ g : coordSubalg (K := K), ‖(g : C(K, ℝ)) - f‖ < ε :=
  ContinuousMap.exists_mem_subalgebra_near_continuousMap_of_separatesPoints
    (A := coordSubalg (K := K))
    (w := coordSubalg_separatesPoints (K := K))
    (f := f) (ε := ε) (pos := hε)

end StoneWeierstrass

end NN.MLTheory.Proofs.UniversalApproximation
