/-
Copyright (c) 2026 TorchLean contributors
Released under MIT license as described in the file LICENSE.
Authors: TorchLean contributors
-/
module

public import NN.Tensor.Internal.Check.Diagnostic
public import NN.Tensor.Internal.Representation.Shape
public import NN.Tensor.Internal.Syntax.Parser -- shake: keep

/-!
# Normalized transformation patterns

Normalization expands ellipses against a statically known input rank and replaces
surface axes by stable elementary-axis identifiers. The result carries the
rank and operation-specific well-formedness facts needed by later checking
and semantics.
-/

public section

namespace TorchLean.Tensor.Internal.Check

open TorchLean.Tensor.Internal.Syntax

universe u

/-- The three transformation modes with distinct axis-set rules. -/
inductive TransformKind where
  /-- Permute and reshape axes without creating or reducing elements. -/
  | rearrange
  /-- Insert and replicate axes while preserving every input axis. -/
  | repeat
  /-- Remove input axes with an explicitly chosen reduction. -/
  | reduce
deriving Repr, @[expose] BEq, @[expose] ReflBEq,
  @[expose] LawfulBEq, @[expose] DecidableEq

attribute [implicit_reducible]
  instBEqTransformKind instDecidableEqTransformKind

/-- Stable identity of an elementary axis after ellipsis expansion. -/
inductive AxisId where
  /-- A logical axis identified by its source name. -/
  | named (name : String)
  /-- A numeric axis identified by both its length and source occurrence. -/
  | anonymous (value occurrence : Nat)
  /-- One concrete dimension generated by expanding an ellipsis. -/
  | ellipsis (index : Nat)
deriving Repr, @[expose] BEq, @[expose] ReflBEq,
  @[expose] LawfulBEq, @[expose] DecidableEq

attribute [implicit_reducible]
  instBEqAxisId instDecidableEqAxisId

namespace AxisId

/-- Whether an axis is an anonymous numeric occurrence. -/
@[expose, implicit_reducible]
def isAnonymous : AxisId → Bool
  | .anonymous _ _ => true
  | _ => false

end AxisId

namespace Impl

/--
Expand one parsed axis into its elementary normalized axes.

This helper is exposed only because elaborated transformation certificates
reduce `expandExpression` in downstream modules.
-/
@[expose, implicit_reducible]
def expandAxis (ellipsisAxes : List AxisId) (axis : Axis) : List AxisId :=
  match axis with
  | .named name => [.named name]
  | .anonymous value occurrence => [.anonymous value occurrence]
  | .unit => []
  | .ellipsis => ellipsisAxes

/--
Whether a physical axis consists solely of an unparenthesized ellipsis.

The distinction matters because a bare ellipsis contributes several physical
dimensions, whereas a parenthesized ellipsis remains one composite dimension.
-/
@[expose, implicit_reducible]
def isBareEllipsis (axis : CompositeAxis) : Bool :=
  match axis.parenthesized, axis.axes with
  | false, [item] => item.value == .ellipsis
  | _, _ => false

end Impl

/-- Expand one composition, splitting a bare ellipsis into separate dimensions. -/
@[expose, implicit_reducible]
def expandComposite (ellipsisAxes : List AxisId)
    (axis : CompositeAxis) : List (List AxisId) :=
  if Impl.isBareEllipsis axis then
    ellipsisAxes.map fun item => [item]
  else
    [axis.axes.flatMap fun item => Impl.expandAxis ellipsisAxes item.value]

/-- Expand every composition in an expression against rank-generated ellipsis axes. -/
@[expose, implicit_reducible]
def expandExpression (ellipsisAxes : List AxisId)
    (expression : Expression) : List (List AxisId) :=
  expression.axes.flatMap (expandComposite ellipsisAxes)

/-- Whether every elementary axis in `left` also occurs in `right`. -/
@[expose, implicit_reducible]
def axesSubset (left right : List AxisId) : Bool :=
  left.all fun axis => decide (axis ∈ right)

/-- The Boolean subset test exactly expresses list-element containment. -/
theorem axesSubset_eq_true_iff {left right : List AxisId} :
    axesSubset left right = true ↔
      ∀ ⦃axis⦄, axis ∈ left → axis ∈ right := by
  simp [axesSubset]

namespace Impl

/--
Whether a normalized axis list contains a numeric anonymous axis.

This helper remains under `Internal`; its body is visible so generated
well-formedness certificates can reduce `anonymousAxesAllowed`.
-/
@[expose, implicit_reducible]
def hasAnonymous (axes : List AxisId) : Bool :=
  axes.any AxisId.isAnonymous

end Impl

/-- A transformation pattern after rank-specific ellipsis expansion. -/
structure NormalizedTransform where
  /-- Operation whose axis-set rules the normalized pattern must satisfy. -/
  kind : TransformKind
  /-- Original parsed pattern, retained for diagnostics and source conventions. -/
  source : TransformPattern
  /-- Physical input against which the left side was normalized. -/
  input : Shape
  /-- Number of physical dimensions represented by the input ellipsis. -/
  ellipsisRank : Nat
  /-- Fresh logical axes replacing the ellipsis, in physical order. -/
  ellipsisAxes : List AxisId
  /-- Elementary input axes grouped by physical input dimension. -/
  inputGroups : List (List AxisId)
  /-- Elementary output axes grouped by physical output dimension. -/
  outputGroups : List (List AxisId)

namespace NormalizedTransform

/-- Elementary input axes in source order. -/
@[expose, implicit_reducible]
def inputAxes (normalized : NormalizedTransform) : List AxisId :=
  normalized.inputGroups.flatten

/-- Elementary output axes in source order. -/
@[expose, implicit_reducible]
def outputAxes (normalized : NormalizedTransform) : List AxisId :=
  normalized.outputGroups.flatten

/-- The axis-set condition associated with the selected transformation mode. -/
@[expose, implicit_reducible]
def axisRelation (normalized : NormalizedTransform) : Bool :=
  match normalized.kind with
  | .rearrange =>
      axesSubset normalized.inputAxes normalized.outputAxes &&
        axesSubset normalized.outputAxes normalized.inputAxes
  | .repeat => axesSubset normalized.inputAxes normalized.outputAxes
  | .reduce => axesSubset normalized.outputAxes normalized.inputAxes

/-- Whether the mode permits all anonymous axes present in the pattern. -/
@[expose, implicit_reducible]
def anonymousAxesAllowed (normalized : NormalizedTransform) : Bool :=
  normalized.kind != .rearrange ||
    (!Impl.hasAnonymous normalized.inputAxes &&
      !Impl.hasAnonymous normalized.outputAxes)

/-- The rank equation determining the number of expanded ellipsis axes. -/
@[expose, implicit_reducible]
def ellipsisRankValid (normalized : NormalizedTransform) : Prop :=
  if normalized.source.left.ellipsisCount = 0 then
    normalized.ellipsisRank = 0
  else
    normalized.source.left.axes.length - 1 + normalized.ellipsisRank =
      normalized.input.length

/--
The ellipsis rank equation is constructively decidable from the finite
pattern and shape data.
-/
instance (normalized : NormalizedTransform) :
    Decidable normalized.ellipsisRankValid := by
  unfold ellipsisRankValid
  infer_instance

/-- All structural facts established by normalization. -/
structure Valid (normalized : NormalizedTransform) : Prop where
  /-- The input expression contains at most one ellipsis. -/
  left_ellipsis_unique : normalized.source.left.ellipsisCount ≤ 1
  /-- The output expression contains at most one ellipsis. -/
  right_ellipsis_unique : normalized.source.right.ellipsisCount ≤ 1
  /-- An input ellipsis occupies a complete physical-axis position. -/
  left_ellipsis_bare :
    normalized.source.left.hasParenthesizedEllipsis = false
  /-- An output ellipsis is present only when the input supplies its axes. -/
  right_ellipsis_has_source :
    normalized.source.right.ellipsisCount = 0 ∨
      normalized.source.left.ellipsisCount = 1
  /-- The expanded ellipsis rank agrees with the physical input rank. -/
  ellipsis_rank : normalized.ellipsisRankValid
  /-- Ellipsis axes are the canonical fresh identifiers in physical order. -/
  ellipsis_axes :
    normalized.ellipsisAxes =
      (List.range normalized.ellipsisRank).map AxisId.ellipsis
  /-- Input groups are exactly the rank-specific expansion of the source syntax. -/
  input_expansion :
    normalized.inputGroups =
      expandExpression normalized.ellipsisAxes normalized.source.left
  /-- Output groups are exactly the rank-specific expansion of the target syntax. -/
  output_expansion :
    normalized.outputGroups =
      expandExpression normalized.ellipsisAxes normalized.source.right
  /-- Expanded input groups correspond one-for-one with physical dimensions. -/
  input_rank : normalized.inputGroups.length = normalized.input.length
  /-- Every elementary input axis has a unique semantic occurrence. -/
  input_nodup : normalized.inputAxes.Nodup
  /-- Every elementary output axis has a unique semantic occurrence. -/
  output_nodup : normalized.outputAxes.Nodup
  /-- Input and output axis sets obey the selected operation's rule. -/
  axis_relation : normalized.axisRelation = true
  /-- Anonymous numeric axes occur only in modes where their semantics is defined. -/
  anonymous_axes : normalized.anonymousAxesAllowed = true

namespace Valid

/-- Rearrange preserves every input elementary axis in its output. -/
theorem input_axes_subset_output_of_rearrange
    {normalized : NormalizedTransform} (valid : normalized.Valid)
    (hKind : normalized.kind = .rearrange) :
    ∀ ⦃axis⦄, axis ∈ normalized.inputAxes → axis ∈ normalized.outputAxes := by
  have hRelation := valid.axis_relation
  simp only [axisRelation, hKind, Bool.and_eq_true, axesSubset_eq_true_iff] at hRelation
  exact hRelation.1

/-- Rearrange introduces no output elementary axis absent from its input. -/
theorem output_axes_subset_input_of_rearrange
    {normalized : NormalizedTransform} (valid : normalized.Valid)
    (hKind : normalized.kind = .rearrange) :
    ∀ ⦃axis⦄, axis ∈ normalized.outputAxes → axis ∈ normalized.inputAxes := by
  have hRelation := valid.axis_relation
  simp only [axisRelation, hKind, Bool.and_eq_true, axesSubset_eq_true_iff] at hRelation
  exact hRelation.2

/-- Repeat retains every input elementary axis and may add new output axes. -/
theorem input_axes_subset_output_of_repeat
    {normalized : NormalizedTransform} (valid : normalized.Valid)
    (hKind : normalized.kind = .repeat) :
    ∀ ⦃axis⦄, axis ∈ normalized.inputAxes → axis ∈ normalized.outputAxes := by
  have hRelation := valid.axis_relation
  simpa only [axisRelation, hKind, axesSubset_eq_true_iff] using hRelation

/-- Reduce retains only elementary axes already present in its input. -/
theorem output_axes_subset_input_of_reduce
    {normalized : NormalizedTransform} (valid : normalized.Valid)
    (hKind : normalized.kind = .reduce) :
    ∀ ⦃axis⦄, axis ∈ normalized.outputAxes → axis ∈ normalized.inputAxes := by
  have hRelation := valid.axis_relation
  simpa only [axisRelation, hKind, axesSubset_eq_true_iff] using hRelation

end Valid

end NormalizedTransform

/-- A normalized pattern bundled with its machine-checked invariant. -/
structure CheckedNormalization where
  /-- Normalized transformation data consumed by shape resolution. -/
  value : NormalizedTransform
  /-- Proof that normalization established every structural invariant. -/
  valid : value.Valid

/--
Compute the ellipsis rank while checking that the left pattern matches the
physical input rank.
-/
private def checkRank (pattern : TransformPattern) (inputShape : Shape) :
    Result Nat :=
  let leftEllipses := pattern.left.ellipsisCount
  if leftEllipses = 0 then
    if pattern.left.axes.length = inputShape.length then
      .ok 0
    else
      .error
        { code := .rankMismatch
          message := "input rank does not match the left side of the pattern"
          span := pattern.left.span }
  else
    let fixedRank := pattern.left.axes.length - 1
    if fixedRank ≤ inputShape.length then
      .ok (inputShape.length - fixedRank)
    else
      .error
        { code := .rankMismatch
          message := "input rank is too small for the pattern ellipsis"
          span := pattern.left.span }

/-- Construct a source-located invalid-ellipsis diagnostic. -/
private def invalidEllipsis {α : Type u} (message : String) (span : Span) : Result α :=
  .error { code := .invalidEllipsis, message, span }

/--
Expand a parsed transformation pattern against a concrete input rank.

The returned proof records rank agreement, ellipsis expansion, uniqueness of
elementary axes, and the mode-specific axis relation.
-/
def normalize (kind : TransformKind) (pattern : TransformPattern)
    (inputShape : Shape) : Result CheckedNormalization := do
  if hLeftUnique : pattern.left.ellipsisCount ≤ 1 then
    if hRightUnique : pattern.right.ellipsisCount ≤ 1 then
      if hLeftBare : pattern.left.hasParenthesizedEllipsis = false then
        if hRightSource :
            pattern.right.ellipsisCount = 0 ∨ pattern.left.ellipsisCount = 1 then
          let ellipsisRank ← checkRank pattern inputShape
          let ellipsisAxes := (List.range ellipsisRank).map AxisId.ellipsis
          let candidate : NormalizedTransform :=
            { kind
              source := pattern
              input := inputShape
              ellipsisRank
              ellipsisAxes
              inputGroups := expandExpression ellipsisAxes pattern.left
              outputGroups := expandExpression ellipsisAxes pattern.right }
          if hEllipsisRank : candidate.ellipsisRankValid then
            if hInputRank : candidate.inputGroups.length = candidate.input.length then
              if hInputNodup : candidate.inputAxes.Nodup then
                if hOutputNodup : candidate.outputAxes.Nodup then
                  if hAnonymous : candidate.anonymousAxesAllowed = true then
                    if hAxisRelation : candidate.axisRelation = true then
                      .ok
                        ⟨candidate,
                          { left_ellipsis_unique := hLeftUnique
                            right_ellipsis_unique := hRightUnique
                            left_ellipsis_bare := hLeftBare
                            right_ellipsis_has_source := hRightSource
                            ellipsis_rank := hEllipsisRank
                            ellipsis_axes := rfl
                            input_expansion := rfl
                            output_expansion := rfl
                            input_rank := hInputRank
                            input_nodup := hInputNodup
                            output_nodup := hOutputNodup
                            axis_relation := hAxisRelation
                            anonymous_axes := hAnonymous }⟩
                    else
                      .error
                        { code := .axisMismatch
                          message := "axes on the two sides are incompatible with the operation"
                          span := pattern.span }
                  else
                    .error
                      { code := .anonymousAxisInRearrange
                        message := "rearrange permits only unit anonymous axes"
                        span := pattern.span }
                else
                  .error
                    { code := .axisMismatch
                      message := "expanded output axes are not unique"
                      span := pattern.right.span }
              else
                .error
                  { code := .axisMismatch
                    message := "expanded input axes are not unique"
                    span := pattern.left.span }
            else
              .error
                { code := .internalInvariant
                  message := "normalization produced an inconsistent input rank"
                  span := pattern.left.span }
          else
            .error
              { code := .internalInvariant
                message := "normalization produced an inconsistent ellipsis rank"
                span := pattern.left.span }
        else
          invalidEllipsis
            "an output ellipsis requires an input ellipsis" pattern.right.span
      else
        invalidEllipsis "the input ellipsis may not be parenthesized" pattern.left.span
    else
      invalidEllipsis "an expression may contain only one ellipsis" pattern.right.span
  else
    invalidEllipsis "an expression may contain only one ellipsis" pattern.left.span

end TorchLean.Tensor.Internal.Check
