/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import Batteries.Data.Float.Basic
public import NN.API
public import NN.Floats
public import NN.Widgets
/-!
# Float32 Semantics
This tutorial runs the same compact MLP under two executable binary32 semantics:
- `Float32`: Lean's native binary32 type and runtime implementation;
- `FloatLib.Floats.ExecFloat.Binary 8 23`: FloatLib's configured executable binary32 model.
We run a single forward pass and a single reverse-mode VJP (seeded with `1.0`) and then report
`max_abs_diff` between native Float32 and configured binary32 after converting both results to host
`Float`
for display.
PyTorch comparison:
```python
import torch
from torch import nn

model = nn.Sequential(nn.Linear(2, 3), nn.ReLU(), nn.Linear(3, 1)).to(torch.float32)

# PyTorch runs the model through its selected float32 kernels.
```

The TorchLean example adds an independent second execution. Lean's native `Float32` supplies the
ordinary runtime path, while `ExecFloat.Binary 8 23` computes from explicit binary32 fields and
rounding rules.
The model and autograd program stay unchanged because their element type is generic.

Run:
  `lake exe torchlean float32_semantics`

For editor inspection, put the cursor on the `#float32_*` commands below. Those widgets are for
visualization only; the actual tutorial code uses ordinary `def` and `IO` definitions.
-/

@[expose] public section

open FloatLib.Floats (ExecFloat)
open FloatLib.Floats.ExecFloat (Binary)
open FloatLib.Floats.ExecFloat.Binary (ofModel toModel)
open FloatLib.Floats.Formats.BinaryInterchange (Model FloatFormat)

open Spec TorchLean
open TorchLean.Tensor
open TorchLean.Floats.IEEE754

namespace NN.Examples.DeepDives.Floats.Float32Semantics

/-
This tutorial uses the public TorchLean surface:

- models: `nn.Sequential` built from `nn.*`
- execution: `nn.lowerToTypedGraph model` + `graph.forward`
- autodiff: `autograd.model.vjp`

No `Runtime.Autograd.*` tape/session machinery appears in this file.
-/

/-! ## Float32 widget probes -/

/--
`0.1` is the canonical "not exactly representable" decimal. The widget shows the binary32 value
that `ExecFloat.Binary 8 23` receives after rounding from the host literal.

PyTorch analogue:

```python
torch.tensor(0.1, dtype=torch.float32)
```
-/
def decimalTenth : Float := 0.1

/-- A simple finite binary32 value for the bit-layout widget. -/
def one32 : Binary 8 23 := (fun x => (ofModel (Model.cast .binary64 .binary32 (toModel
  (Binary.ofFloat x))) : Binary 8 23)) 1.0

/-- Canonical quiet NaN, useful for showing classification and comparison behavior. -/
def quietNaN32 : Binary 8 23 := (Binary.canonicalNaN : Binary 8 23)

#float32_round_view decimalTenth
#float32_view one32
#float32_view quietNaN32
#float32_compare_view one32, quietNaN32

/-- The network this tutorial runs twice, once in `Float` and once in `Float32`. -/
abbrev model : nn.Sequential [2] [1] :=
  -- A compact 2-layer MLP with ReLU:
  --   Linear(2 -> 3) -> ReLU -> Linear(3 -> 1)
  --
  -- This uses the public `nn` surface (PyTorch-like layer stacking and named configs).
  --
  -- Note: this tutorial supplies *explicit* parameter tensors below, so the init seeds are
  -- irrelevant here.
  nn.build 0 <| nn.mlp 2 1 { hiddenWidths := [3], activation := .relu }

/-- Parameter and buffer layout generated by the two affine layers in `model`. -/
abbrev modelStateLayout : List Shape :=
  [Shape.ofList [3, 2], Shape.ofList [3], Shape.ofList [1, 3], Shape.ofList [1]]

/-- The model builder produces exactly `modelStateLayout`. -/
theorem model_stateShapes :
    nn.stateShapes model = modelStateLayout := by
  rfl

/-- Named outputs from one forward and reverse-mode execution. -/
structure RunResult (α : Type) [Storage α] where
  output : Tensor α [1]
  hiddenWeightGrad : Tensor α [3, 2]
  hiddenBiasGrad : Tensor α [3]
  outputWeightGrad : Tensor α [1, 3]
  outputBiasGrad : Tensor α [1]
  inputGrad : Tensor α [2]

namespace RunResult

/-- Convert every tensor in a run result while preserving its statically known shape. -/
def map {α β : Type} [Storage α] [Storage β]
    (result : RunResult α)
    (f : ∀ {shape}, Tensor α shape → Tensor β shape) :
    RunResult β where
  output := f result.output
  hiddenWeightGrad := f result.hiddenWeightGrad
  hiddenBiasGrad := f result.hiddenBiasGrad
  outputWeightGrad := f result.outputWeightGrad
  outputBiasGrad := f result.outputBiasGrad
  inputGrad := f result.inputGrad

end RunResult

/--
Run one forward and backward pass over the fixed parameters at scalar type `α`.

The whole tutorial rests on this being generic in `α`: the same code, the same literals and the same
graph run at `Float` and at `Float32`, so any difference in the printed numbers comes from the
arithmetic and nothing else.
-/
def runOnce {α : Type}
    [Storage α] [Context α] [ToString α]
    [Runtime.FromFloat α]
    (tag : String) : IO (RunResult α) := do
  -- Public data boundaries use `Float` literals and convert them into the selected scalar `α`.
  let cast : Float → α := Runtime.ofFloat

  /-
  ### 1. Explicit parameters

  PyTorch analogue:

  ```python
  with torch.no_grad():
      model[0].weight.copy_(torch.tensor([[0.1, 0.2], [0.3, 0.4], [0.5, 0.6]]))
      model[0].bias.copy_(torch.tensor([0.1, 0.2, 0.3]))
      model[2].weight.copy_(torch.tensor([[0.7, 0.8, 0.9]]))
      model[2].bias.copy_(torch.tensor([0.4]))
  ```

  `autograd.model.State model α` is shape-indexed model state. The model determines every entry
  shape, so replacing a parameter with an incompatible tensor is rejected during elaboration.
  -/
  let hiddenWeight : Tensor α [3, 2] :=
    Tensor.map cast ([[0.1, 0.2], [0.3, 0.4], [0.5, 0.6]] : Tensor Float [3, 2])
  let hiddenBias : Tensor α [3] :=
    Tensor.map cast ([0.1, 0.2, 0.3] : Tensor Float [3])
  let outputWeight : Tensor α [1, 3] :=
    Tensor.map cast ([[0.7, 0.8, 0.9]] : Tensor Float [1, 3])
  let outputBias : Tensor α [1] :=
    Tensor.map cast ([0.4] : Tensor Float [1])
  let paramsByLayer : nn.State α modelStateLayout :=
    nn.State.empty
      |>.push hiddenWeight
      |>.push hiddenBias
      |>.push outputWeight
      |>.push outputBias
  let params : autograd.model.State model α :=
    paramsByLayer.cast model_stateShapes.symm

  -- One input vector x in R^2.
  let x : Tensor α [2] :=
    Tensor.map cast ([0.5, 0.8] : Tensor Float [2])

  /-
  ### 2. Forward pass

  PyTorch analogue:

  ```python
  y = model(x)
  ```

  `nn.lowerToTypedGraph` records the model's forward program as a reusable typed SSA graph.
  TorchLean models are scalar-generic, so this step chooses the scalar `α` used by that executable
  graph.
  -/
  let graph ← nn.lowerToTypedGraph model (α := α)
  -- Run `y = model(params, x)` (single-example predict; no batching here).
  let y := nn.TypedGraphModel.forward graph params x

  /-
  ### 3. Reverse-mode VJP

  PyTorch analogue:

  ```python
  y.sum().backward()
  dState = [p.grad for p in model.parameters()]
  inputGrad = x.grad
  ```

  A VJP needs an upstream output gradient. Since the output shape is `[1]`, seeding with `[1]`
  computes the same result as differentiating `sum(y)`.
  -/
  let outputGradient : Tensor α [1] :=
    Tensor.full [1] (cast 1.0)

  -- State and input gradients come from the same reverse pass.
  let (dState, inputGrad) ← autograd.model.vjp (α := α) model params x outputGradient

  /- TorchLean keeps each parameter-gradient shape in the type of the gradient pack. -/
  let gradientsByLayer := dState.cast model_stateShapes
  let hiddenWeightGrad := gradientsByLayer.get 0
  let hiddenBiasGrad := gradientsByLayer.get 1
  let outputWeightGrad := gradientsByLayer.get 2
  let outputBiasGrad := gradientsByLayer.get 3

  IO.println s!"== {tag} =="
  IO.println s!"y   = {Spec.pretty y}"
  IO.println s!"hiddenWeightGrad = {Spec.pretty hiddenWeightGrad}"
  IO.println s!"hiddenBiasGrad = {Spec.pretty hiddenBiasGrad}"
  IO.println s!"outputWeightGrad = {Spec.pretty outputWeightGrad}"
  IO.println s!"outputBiasGrad = {Spec.pretty outputBiasGrad}"
  IO.println s!"inputGrad  = {Spec.pretty inputGrad}"

  pure { output := y, hiddenWeightGrad, hiddenBiasGrad, outputWeightGrad, outputBiasGrad,
         inputGrad }

/--
Largest difference across every tensor in a run: the output, all four parameter gradients and the
input gradient. One number summarizing how far the two precisions drifted apart.
-/
def maxAbsDiffResult (a b : RunResult Float) : Float :=
  let differences : Tensor Float [6] :=
    [ Tensor.maxAbsDiff a.output b.output
    , Tensor.maxAbsDiff a.hiddenWeightGrad b.hiddenWeightGrad
    , Tensor.maxAbsDiff a.hiddenBiasGrad b.hiddenBiasGrad
    , Tensor.maxAbsDiff a.outputWeightGrad b.outputWeightGrad
    , Tensor.maxAbsDiff a.outputBiasGrad b.outputBiasGrad
    , Tensor.maxAbsDiff a.inputGrad b.inputGrad ]
  Tensor.maxAbs differences

/-- Command-line help for the Float32 semantics tutorial. -/
def usage : String :=
  String.intercalate "\n"
    [ "TorchLean Float32 semantics tutorial"
    , ""
    , "Usage:"
    , "  lake exe torchlean float32_semantics"
    , ""
    , "This demo has no tutorial-specific flags."
    ]

/-- Entry point. -/
def main (args : List String) : IO Unit := do
  let args := CLI.dropDashDash args
  if CLI.hasHelp args then
    IO.println usage
    return
  CLI.requireNoArgs "float32_semantics" args
  IO.println "== Float32 semantics tutorial =="
  IO.println
    "Note: rounded-real binary32 is proof-only and is selected directly in theorem statements."
  IO.println "[TorchLean] FP32: finite rounded-real proof model"
  IO.println "[TorchLean] configured binary32: bit-level binary32 reference"

  let rNative ← runOnce (α := Float32) "Float32 (native runtime)"
  let r32 ← runOnce (α := (Binary 8 23)) "ExecFloat.Binary 8 23"

  let rNativeF : RunResult Float :=
    rNative.map fun {_shape} t => Tensor.map Float32.toFloat t
  let r32F : RunResult Float :=
    r32.map fun {_shape} t =>
      Tensor.map (fun x => Binary.toFloat (ofModel (Model.cast .binary32 .binary64 (toModel x)))) t

  let diff := maxAbsDiffResult rNativeF r32F
  IO.println s!"max_abs_diff(Float32 vs configured binary32) = {diff.toStringFull}"

end NN.Examples.DeepDives.Floats.Float32Semantics
