"""
Create a Transformer encoder reference in PyTorch and export its parameters to JSON for TorchLean.

The JSON schema matches the importer in:

  `NN/Runtime/PyTorch/Import/Transformer.lean`

with explicit keys:
  `Wq`, `Wk`, `Wv`, `Wo`, `W1`, `W2`, `b1`, `b2`,
  `norm1_gamma`, `norm1_beta`, `norm2_gamma`, `norm2_beta`.

Run from the repo root:

  `python3 NN/Examples/Interop/PyTorch/Transformer/train_transformer.py`

Design note:
The attention block is bias-free (`q_proj/k_proj/v_proj/out_proj` have `bias=False`) because
TorchLean's executable attention layer uses explicit projection matrices without bias terms.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import torch
import torch.nn as nn
import torch.nn.functional as F

THIS_DIR = Path(__file__).resolve().parent

class MultiHeadAttention(nn.Module):
    """Small multi-head attention block with explicit Q/K/V/O projections.

    This mirrors the structure generated by TorchLean's exporter in:
      `NN/Runtime/PyTorch/Export/Transformer.lean`

    Important: projections are bias-free to match TorchLean's runtime (`Wq/Wk/Wv/Wo`).
    """

    def __init__(self, embed_dim: int = 2, num_heads: int = 1) -> None:
        super().__init__()
        self.embed_dim = embed_dim
        self.num_heads = num_heads
        self.head_dim = embed_dim // num_heads
        assert embed_dim % num_heads == 0
        self.q_proj = nn.Linear(embed_dim, embed_dim, bias=False)
        self.k_proj = nn.Linear(embed_dim, embed_dim, bias=False)
        self.v_proj = nn.Linear(embed_dim, embed_dim, bias=False)
        self.out_proj = nn.Linear(embed_dim, embed_dim, bias=False)

    def forward(self, x: torch.Tensor, mask: torch.Tensor | None = None) -> torch.Tensor:
        # x: (batch, seq_len, embed_dim)
        B, S, E = x.shape
        q = self.q_proj(x).view(B, S, self.num_heads, self.head_dim).transpose(1, 2)
        k = self.k_proj(x).view(B, S, self.num_heads, self.head_dim).transpose(1, 2)
        v = self.v_proj(x).view(B, S, self.num_heads, self.head_dim).transpose(1, 2)
        scores = torch.matmul(q, k.transpose(-2, -1)) / math.sqrt(self.head_dim)
        if mask is not None:
            scores = scores.masked_fill(mask == 0, float("-inf"))
        attn = torch.softmax(scores, dim=-1)
        out = torch.matmul(attn, v)
        out = out.transpose(1, 2).contiguous().view(B, S, E)
        return self.out_proj(out)


class FeedForward(nn.Module):
    def __init__(self, embed_dim: int = 2, hidden_dim: int = 2) -> None:
        super().__init__()
        self.fc1 = nn.Linear(embed_dim, hidden_dim, bias=True)
        self.fc2 = nn.Linear(hidden_dim, embed_dim, bias=True)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        return self.fc2(F.relu(self.fc1(x)))


class TinyTransformerEncoder(nn.Module):
    def __init__(self, embed_dim: int = 2, num_heads: int = 1, hidden_dim: int = 2, num_layers: int = 1):
        super().__init__()
        self.layers = nn.ModuleList(
            [
                nn.ModuleDict(
                    {
                        "mha": MultiHeadAttention(embed_dim=embed_dim, num_heads=num_heads),
                        "norm1": nn.LayerNorm(embed_dim),
                        "ffn": FeedForward(embed_dim=embed_dim, hidden_dim=hidden_dim),
                        "norm2": nn.LayerNorm(embed_dim),
                    }
                )
                for _ in range(num_layers)
            ]
        )

    def forward(self, x: torch.Tensor, mask: torch.Tensor | None = None) -> torch.Tensor:
        for layer in self.layers:
            attn_out = layer["mha"](x, mask)
            x = layer["norm1"](x + attn_out)
            ffn_out = layer["ffn"](x)
            x = layer["norm2"](x + ffn_out)
        return x


def save_transformer_encoder_to_json(model: TinyTransformerEncoder, json_path: str) -> None:
    """Save a single-layer Transformer encoder weights to JSON matching TorchLean's importer."""
    if len(model.layers) != 1:
        raise ValueError("This example exporter supports num_layers=1.")

    layer = model.layers[0]
    mha: MultiHeadAttention = layer["mha"]  # type: ignore[assignment]
    ffn: FeedForward = layer["ffn"]         # type: ignore[assignment]
    norm1: nn.LayerNorm = layer["norm1"]    # type: ignore[assignment]
    norm2: nn.LayerNorm = layer["norm2"]    # type: ignore[assignment]

    # Attention projections use TorchLean's mathematical (input, output) layout.
    # Feed-forward weights retain PyTorch's native (output, input) layout.
    data: dict[str, object] = {}
    data["Wq"] = mha.q_proj.weight.detach().t().tolist()
    data["Wk"] = mha.k_proj.weight.detach().t().tolist()
    data["Wv"] = mha.v_proj.weight.detach().t().tolist()
    data["Wo"] = mha.out_proj.weight.detach().t().tolist()

    data["W1"] = ffn.fc1.weight.detach().tolist()
    data["b1"] = ffn.fc1.bias.detach().tolist()
    data["W2"] = ffn.fc2.weight.detach().tolist()
    data["b2"] = ffn.fc2.bias.detach().tolist()

    data["norm1_gamma"] = norm1.weight.detach().tolist()
    data["norm1_beta"] = norm1.bias.detach().tolist()
    data["norm2_gamma"] = norm2.weight.detach().tolist()
    data["norm2_beta"] = norm2.bias.detach().tolist()

    payload = {
        "params": data,
        "meta": {
            "format": "TorchLean.TransformerEncoder",
            "dtype": "float32",
        },
    }

    with open(json_path, "w") as f:
        json.dump(payload, f, indent=2)


def main():
    torch.manual_seed(0)
    model = TinyTransformerEncoder(embed_dim=2, num_heads=1, hidden_dim=2, num_layers=1)
    # Fixed input to match Lean (seqLen=1, embedDim=2), all elements 1.5
    x = torch.full((1, 1, 2), 1.5, dtype=torch.float32)
    y = model(x)
    print('Input:', x)
    print('Output shape:', y.shape)
    print('Output:', y)

    out_path = THIS_DIR / "transformer_encoder.json"
    save_transformer_encoder_to_json(model, str(out_path))
    print(f"Saved Transformer encoder weights to {out_path}")

if __name__ == '__main__':
    main()
