/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import NN.Verification.Geometry3D.Box3D
public import NN.API.CLI.Parser

/-!
# Geometry3D CLI wrapper

This module keeps the runnable `camera-box3d-cert` entrypoint next to the reusable verifier.

The example artifacts are generated by `scripts/verification/geometry3d/*` under `External`.
The default path here is a deterministic sample certificate so the CLI can be exercised without
network access, GPU access, or model downloads.
-/

@[expose] public section

namespace NN.Verification.Geometry3D.CLI

open NN.Verification.Geometry3D.Box3D

/-- Default sample certificate used when no path is passed to `lake exe verify`. -/
def defaultCertPath : String :=
  "NN/Verification/Geometry3D/check_box3d_camera_cert.json"

/-- Check an exported JSON camera-box certificate artifact. -/
def verifyCert (path : String := defaultCertPath) : IO Unit :=
  checkOrThrow path

/-- CLI entrypoint used by the unified verification dispatcher. -/
def main (args : List String) : IO Unit := do
  let args := TorchLean.CLI.normalizePathFlag args "cert" defaultCertPath
  let (path, args) ←
    match TorchLean.CLI.takeFlagValue args "cert" (default := defaultCertPath) with
    | .ok result => pure result
    | .error e => throw <| IO.userError e
  IO.ofExcept <| TorchLean.CLI.checkNoArgs args
  verifyCert path

end NN.Verification.Geometry3D.CLI
