/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import NN.Runtime.Autograd.IRExec.Correctness.Common

/-!
# Semantic Equivalence: Empty Prefix and Permutations

The empty-prefix lemma initializes the recursive graph proof. The permutation lemmas relate
shape-erased adjacent swaps to the typed swap program used by concat, transpose, and permute.
General parent lookup, output normalization, and tail composition live in `Correctness.Common`.
-/

@[expose] public section

namespace Runtime
namespace Autograd
namespace IRExec

open Spec TorchLean
open Proofs.Autograd.Algebra
open NN.IR
open Internal

/-!
## Correctness (Semantic Equivalence Helpers)

These lemmas are shared by the branch-by-branch proof in `Correctness.SemanticEquivalence`.
-/

/-- Base case: evaluating the empty lowered prefix yields the singleton table containing just the
  input. -/
@[simp]
theorem denoteAllState_nil {α : Type} [TorchLean.Storage α] [Context α]
    {inShape : Shape} (x : Tensor α inShape) :
    denoteAllState (α := α) inShape (st := (⟨[], .nil⟩ : State α inShape)) x =
      #[Spec.SomeTensor.ofTensor x] := by
  simp [denoteAllState, execOfState, ForwardGraph.denoteAll, ForwardGraph.eval,
    Spec.SomeTensor.ofTensor, TorchLean.TensorPack.toShapeErasedArray]

attribute [grind =] denoteAllState_nil

/--
Relate shape-erased tensor permutation to `applySwapsTensor`.

This is used to connect `NN.IR.Graph.permuteSomeTensor` to the runtime implementation used by the
node generated by lowering.
-/
theorem applySwapsTensorList_eq_foldl_swapAdjacentAtDepth
    {α : Type} [TorchLean.Storage α] [Context α] {s : Shape} (t : Tensor α s) (swaps : List Nat) :
    (swaps.foldl (fun acc d => Spec.SomeTensor.swapAdjacentAtDepth acc d)
      (Spec.SomeTensor.mk (α := α) s t)) =
      Spec.SomeTensor.mk (α := α) (swapShapeBySwapsList s swaps)
        (applySwapsTensorList (α := α) (s := s) (swaps := swaps) t) := by
  induction swaps generalizing s t with
  | nil =>
      simp [swapShapeBySwapsList, applySwapsTensorList]
  | cons d ds ih =>
      -- Expand one swap step on both sides, then use the induction hypothesis at the updated
      -- shape.  The explicit `change` keeps this proof stable across small simplifier changes.
      change
        (ds.foldl (fun acc d => Spec.SomeTensor.swapAdjacentAtDepth acc d)
            (Spec.SomeTensor.mk (α := α) (s.swapAdjacentAtDepth d)
              (Tensor.swapAdjacentAxes (tensor := t) d))) =
          Spec.SomeTensor.mk (α := α) (swapShapeBySwapsList (s.swapAdjacentAtDepth d) ds)
            (applySwapsTensorList (α := α) (s := s.swapAdjacentAtDepth d) (swaps := ds)
              (Tensor.swapAdjacentAxes (tensor := t) d))
      exact ih (s := s.swapAdjacentAtDepth d) (t := Tensor.swapAdjacentAxes (tensor := t) d)

/--
Specialize `NN.IR.Graph.permuteSomeTensor` to the swap-based implementation used by this lowering
pass.

Given a successful `permute?` witness and computed swap depths, `permuteSomeTensor` returns the
tensor produced by `applySwapsTensor` with the expected final shape.
-/
theorem permuteSomeTensor_eq_applySwapsTensor
    {α : Type} [TorchLean.Storage α] [Context α] {sIn : Shape} (t : Tensor α sIn)
    (perm : Array Nat) (expected : Shape) (swaps : Array Nat)
    (hPerm : Spec.Shape.permute? sIn perm.toList = some expected)
    (hSwaps : NN.IR.Graph.swapDepthsForPerm perm (Spec.Shape.rank sIn) = .ok swaps) :
    NN.IR.Graph.permuteSomeTensor (α := α) (v := Spec.SomeTensor.mk (α := α) sIn t) perm =
      .ok (Spec.SomeTensor.mk (α := α) (swapShapeBySwaps sIn swaps)
        (applySwapsTensor (α := α) (s := sIn) (swaps := swaps) t)) := by
  -- Unfold `permuteSomeTensor`, then rewrite by the permutation witness and swap computation.
  unfold NN.IR.Graph.permuteSomeTensor
  simp [hPerm, hSwaps]
  -- Reduce the fold over shape-erased adjacent swaps to the recursive `applySwapsTensor`.
  simpa [swapShapeBySwaps, applySwapsTensor] using
    (applySwapsTensorList_eq_foldl_swapAdjacentAtDepth
      (α := α) (s := sIn) (t := t) (swaps := swaps.toList))

-- `permuteSomeTensor_eq_applySwapsTensor` carries extra witness parameters (`expected`, `swaps`)
-- that are not uniquely determined from the left-hand side, so it cannot be registered as a
-- `grind` rule.
attribute [grind =] applySwapsTensorList_eq_foldl_swapAdjacentAtDepth

end IRExec
end Autograd
end Runtime
