/-
Copyright (c) 2026 TorchLean
Released under MIT license as described in the file LICENSE.
Authors: TorchLean Team
-/

module

public import NN.Runtime.Autograd.Model.Session.Types
public import NN.Runtime.Autograd.Torch.TypedGraphSession.ShapeIndex

/-!
# Session Tensor Operations

This file is the shared execution-mode dispatch layer for elementary tensor operations. It keeps
the public `Session` API uniform while routing each operation to either the eager tape or the typed
SSA graph session.
-/

@[expose] public section

namespace Runtime
namespace Autograd
namespace Model

open Spec TorchLean
open TorchLean TorchLean.Tensor

namespace Session

/-- Elementwise addition (dispatches by execution mode). -/
def add {α : Type} [TorchLean.Storage α] (s : Session α)
    [Add α] [Zero α] {sh : Shape}
  (a b : Runtime.Autograd.Torch.TensorRef α sh) : IO (Runtime.Autograd.Torch.TensorRef
    α sh) := do
  match s.state with
  | .eager sess => EagerSession.add (α := α) sess (sh := sh) a b
  | .typedGraph sess =>
      Runtime.Autograd.Torch.Internal.TypedGraphSession.add (α := α) sess (sh := sh) a b

/-- Elementwise subtraction (dispatches by execution mode). -/
def sub {α : Type} [TorchLean.Storage α] (s : Session α)
    [Sub α] [Add α] [Zero α] {sh : Shape}
  (a b : Runtime.Autograd.Torch.TensorRef α sh) : IO (Runtime.Autograd.Torch.TensorRef
    α sh) := do
  match s.state with
  | .eager sess => EagerSession.sub (α := α) sess (sh := sh) a b
  | .typedGraph sess =>
      Runtime.Autograd.Torch.Internal.TypedGraphSession.sub (α := α) sess (sh := sh) a b

/-- Elementwise multiplication (dispatches by execution mode). -/
def mul {α : Type} [TorchLean.Storage α] (s : Session α)
    [Mul α] [Add α] [Zero α] {sh : Shape}
  (a b : Runtime.Autograd.Torch.TensorRef α sh) : IO (Runtime.Autograd.Torch.TensorRef
    α sh) := do
  match s.state with
  | .eager sess => EagerSession.mul (α := α) sess (sh := sh) a b
  | .typedGraph sess =>
      Runtime.Autograd.Torch.Internal.TypedGraphSession.mul (α := α) sess (sh := sh) a b

/--
Scale a tensor by a scalar constant `c` (elementwise).

PyTorch analogy: `x * c` or `torch.mul(x, c)`.
-/
def scale {α : Type} [TorchLean.Storage α] (s : Session α)
    [Mul α] [Add α] [Zero α]
  [Runtime.Autograd.Torch.TensorTransfer α] {sh : Shape}
  (x : Runtime.Autograd.Torch.TensorRef α sh) (c : α) :
  IO (Runtime.Autograd.Torch.TensorRef α sh) := do
  match s.state with
  | .eager sess => EagerSession.scale (α := α) sess (sh := sh) x c
  | .typedGraph sess =>
      Runtime.Autograd.Torch.Internal.TypedGraphSession.scale (α := α) sess (sh := sh) x c

/--
Dropout implemented as a Session-level derived op.

In training mode, this records
$$
y=\frac{x\odot\mathtt{mask}}{1-p},
$$

where $\mathtt{mask}\in\{0,1\}$ is generated by the Torch primitive `bernoulliMask`.

## RNG Semantics (JAX-style / functional RNG)

Randomness is a deterministic function of explicit session state:
- we read `(seed, counter)` from the session-level `RngState`,
- derive a per-call `opSeed` deterministically, and
- advance the `RngState` (update `seed`, increment `counter`).

Important: the `bernoulli_mask` op also mixes in a backend-internal counter (approximately: current
tape size / node index). So even with the same `RngState`, changing the surrounding graph structure
can change the exact samples. This is still fully deterministic for a fixed graph.

In evaluation mode (`train=false`) and at `p = 0`, this is the identity. At `p = 1`, training
returns zero. Other values must satisfy $0 < p < 1$.
-/
def dropout {α : Type} [TorchLean.Storage α] [Context α]
    [Runtime.Autograd.Torch.TensorTransfer α]
    (s : Session α) (rng : RngState) {sh : Shape}
    (x : Runtime.Autograd.Torch.TensorRef α sh)
    (p : α) (train : Bool := true) :
    IO (Runtime.Autograd.Torch.TensorRef α sh) := do
  if !train then
    pure x
  else if Context.gtBool 0 p || Context.gtBool p 1 then
    throw <| IO.userError "dropout: expected 0 <= p <= 1"
  else if p == 0 then
    pure x
  else if p == 1 then
    scale (α := α) s (sh := sh) x 0
  else
    let keepProb : α := (1 : α) - p
    have : Decidable (keepProb > (0 : α)) := (Context.decidableGT) keepProb 0
    if _h : keepProb > (0 : α) then
      let seedNat ← getNat (α := α) s rng.seed
      let ctrNat ← getNat (α := α) s rng.counter
      -- Seed is derived deterministically from the explicit `(seed, counter)` state.
      -- Note: `Torch.bernoulli_mask` also mixes in an internal per-graph counter (tape size / node
      -- index), so graph structure can affect the exact samples even with the same `RngState`.
      let opSeed := Random.nextSeed seedNat ctrNat
      setNat (α := α) s rng.seed opSeed
      setNat (α := α) s rng.counter (ctrNat + 1)

      let keepProbRef ← const (α := α) s (sh := Shape.scalar) (Tensor.scalar keepProb)
      let maskRef ←
        match s.state with
        | .eager sess =>
            Runtime.Autograd.Torch.Internal.EagerSession.bernoulliMask (α := α) sess.inner
              (sh := sh) keepProbRef opSeed
        | .typedGraph sess =>
            Runtime.Autograd.Torch.Internal.TypedGraphSession.commitGraphM (α := α) sess
              (β := Runtime.Autograd.Torch.TensorRef α sh)
              (refs := #[keepProbRef.identity?]) (fun {Γ} {ss} xv nat g => do
                let (v, st') ← Runtime.Autograd.Torch.Internal.TypedGraphSession.runGraphM (α := α)
                  (Γ := Γ)
                  (Runtime.Autograd.TypedGraph.GraphM.bernoulliMask (α := α) (Γ := Γ) (s := sh)
                    { id := keepProbRef.id } (seed := opSeed))
                  ss g
                let ⟨ss', g'⟩ := st'
                let st1 : Runtime.Autograd.Torch.Internal.TypedGraphSessionState α :=
                  { Γ := Γ, x := xv, nat := nat, ss := ss', g := g' }
                pure ({ id := v.id }, st1))

      let y ← mul (α := α) s (sh := sh) x maskRef
      let invKeep : α := (1 : α) / keepProb
      scale (α := α) s (sh := sh) y invKeep
    else
      throw <| IO.userError "dropout: expected 0 <= p <= 1"

/-- Elementwise absolute value (dispatches by execution mode). -/
def abs {α : Type} [TorchLean.Storage α] (s : Session α) [Context α]
  [DecidableRel ((· > ·) : α → α → Prop)]
  {sh : Shape} (x : Runtime.Autograd.Torch.TensorRef α sh) :
  IO (Runtime.Autograd.Torch.TensorRef α sh) := do
  match s.state with
  | .eager sess => EagerSession.abs (α := α) sess (sh := sh) x
  | .typedGraph sess =>
      Runtime.Autograd.Torch.Internal.TypedGraphSession.abs (α := α) sess (sh := sh) x

/-- Elementwise square root (dispatches by execution mode). -/
def sqrt {α : Type} [TorchLean.Storage α] (s : Session α) [Context α]
  [DecidableRel ((· > ·) : α → α → Prop)]
  {sh : Shape} (x : Runtime.Autograd.Torch.TensorRef α sh) :
  IO (Runtime.Autograd.Torch.TensorRef α sh) := do
  match s.state with
  | .eager sess => EagerSession.sqrt (α := α) sess (sh := sh) x
  | .typedGraph sess =>
      Runtime.Autograd.Torch.Internal.TypedGraphSession.sqrt (α := α) sess (sh := sh) x

/-- Elementwise clamp to `[minVal, maxVal]` (dispatches by execution mode). -/
def clamp {α : Type} [TorchLean.Storage α] (s : Session α) [Context α]
  [DecidableRel ((· > ·) : α → α → Prop)]
  [Runtime.Autograd.Torch.TensorTransfer α]
  {sh : Shape} (x : Runtime.Autograd.Torch.TensorRef α sh) (minVal maxVal : α) :
  IO (Runtime.Autograd.Torch.TensorRef α sh) := do
  match s.state with
  | .eager sess => EagerSession.clamp (α := α) sess (sh := sh) x minVal maxVal
  | .typedGraph sess =>
      Runtime.Autograd.Torch.Internal.TypedGraphSession.clamp (α := α) sess
        (sh := sh) x minVal maxVal

/-- Elementwise maximum (dispatches by execution mode). -/
def max {α : Type} [TorchLean.Storage α] (s : Session α) [Context α]
  [DecidableRel ((· > ·) : α → α → Prop)]
  {sh : Shape} (a b : Runtime.Autograd.Torch.TensorRef α sh) :
  IO (Runtime.Autograd.Torch.TensorRef α sh) := do
  match s.state with
  | .eager sess => EagerSession.max (α := α) sess (sh := sh) a b
  | .typedGraph sess =>
      Runtime.Autograd.Torch.Internal.TypedGraphSession.max (α := α) sess (sh := sh) a b

/-- Elementwise minimum (dispatches by execution mode). -/
def min {α : Type} [TorchLean.Storage α] (s : Session α) [Context α]
  [DecidableRel ((· > ·) : α → α → Prop)]
  {sh : Shape} (a b : Runtime.Autograd.Torch.TensorRef α sh) :
  IO (Runtime.Autograd.Torch.TensorRef α sh) := do
  match s.state with
  | .eager sess => EagerSession.min (α := α) sess (sh := sh) a b
  | .typedGraph sess =>
      Runtime.Autograd.Torch.Internal.TypedGraphSession.min (α := α) sess (sh := sh) a b

/-- Matrix multiplication with broadcasted batch prefixes. -/
def matmul {α : Type} [TorchLean.Storage α] (s : Session α) [Context α]
  {batchA batchB batch : Shape} {m n p : Nat}
  [broadcastA : Shape.BroadcastTo batchA batch]
  [broadcastB : Shape.BroadcastTo batchB batch]
  (a : Runtime.Autograd.Torch.TensorRef α (batchA.concat [m, n]))
  (b : Runtime.Autograd.Torch.TensorRef α (batchB.concat [n, p])) :
  IO (Runtime.Autograd.Torch.TensorRef α (batch.concat [m, p])) := do
  match s.state with
  | .eager sess =>
      EagerSession.matmul (α := α) sess
        (batchA := batchA) (batchB := batchB) (batch := batch)
        (m := m) (n := n) (p := p) a b
  | .typedGraph sess =>
      Runtime.Autograd.Torch.Internal.TypedGraphSession.matmul (α := α) sess
        (batchA := batchA) (batchB := batchB) (batch := batch)
        (m := m) (n := n) (p := p) a b

/-- Concatenate along the outermost dimension (dimension 0) (dispatches to eager vs typed graph
  backend). -/
def concatLeadingAxis {α : Type} [TorchLean.Storage α] (s : Session α)
    [Context α]
  {n m : Nat} {sh : Shape}
  (a : Runtime.Autograd.Torch.TensorRef α (.dim n sh))
  (b : Runtime.Autograd.Torch.TensorRef α (.dim m sh)) :
  IO (Runtime.Autograd.Torch.TensorRef α (.dim (n + m) sh)) := do
  match s.state with
  | .eager sess => EagerSession.concatLeadingAxis (α := α) sess (n := n) (m := m) (sh := sh) a b
  | .typedGraph sess =>
      Runtime.Autograd.Torch.Internal.TypedGraphSession.concatLeadingAxis (α := α) sess
        (n := n) (m := m) (sh := sh) a b

/--
Slice a contiguous `[start, start+len)` range from dimension 0.

PyTorch analogy: `x[start:start+len]` for the first dimension.
-/
def sliceLeadingAxisRange {α : Type} [TorchLean.Storage α] (s : Session α)
    [Zero α]
  {n : Nat} {sh : Shape}
  (x : Runtime.Autograd.Torch.TensorRef α (.dim n sh)) (start len : Nat) (h : start + len ≤
    n) :
  IO (Runtime.Autograd.Torch.TensorRef α (.dim len sh)) := do
  match s.state with
  | .eager sess =>
      EagerSession.sliceLeadingAxisRange (α := α) sess (n := n) (sh := sh) x start len h
  | .typedGraph sess =>
      Runtime.Autograd.Torch.Internal.TypedGraphSession.sliceLeadingAxisRange (α := α) sess
        (n := n) (sh := sh) x start len h

/-- Apply max pooling over an arbitrary number of spatial axes. -/
def maxPool {α : Type} [TorchLean.Storage α] (s : Session α) [Context α]
    {d channels : Nat} {spatial kernel stride padding : TorchLean.Tensor Nat [d]}
    (x : Runtime.Autograd.Torch.TensorRef α
      (Shape.ofList (channels :: spatial.to (List Nat)))) :
    IO (Runtime.Autograd.Torch.TensorRef α
      (Shape.ofList
        (channels ::
          (Spec.poolOutSpatialPad spatial kernel stride padding).to (List Nat)))) :=
  match s.state with
  | .eager session =>
      EagerSession.maxPool (α := α) session
        (d := d) (channels := channels) (spatial := spatial)
        (kernel := kernel) (stride := stride) (padding := padding) x
  | .typedGraph session =>
      Runtime.Autograd.Torch.Internal.TypedGraphSession.maxPool (α := α) session
        (d := d) (C := channels) (inSpatial := spatial)
        (kernel := kernel) (stride := stride) (padding := padding) x

/-- Apply smooth max pooling over an arbitrary number of spatial axes. -/
def smoothMaxPool {α : Type} [TorchLean.Storage α] (s : Session α) [Context α] [DecidableEq α]
    [Runtime.Autograd.Torch.TensorTransfer α]
    {d channels : Nat} {spatial kernel stride padding : TorchLean.Tensor Nat [d]}
    (x : Runtime.Autograd.Torch.TensorRef α
      (Shape.ofList (channels :: spatial.to (List Nat)))) (beta : α) :
    IO (Runtime.Autograd.Torch.TensorRef α
      (Shape.ofList
        (channels ::
          (Spec.poolOutSpatialPad spatial kernel stride padding).to (List Nat)))) :=
  match s.state with
  | .eager session =>
      EagerSession.smoothMaxPool (α := α) session
        (d := d) (channels := channels) (spatial := spatial)
        (kernel := kernel) (stride := stride) (padding := padding) x beta
  | .typedGraph session =>
      Runtime.Autograd.Torch.Internal.TypedGraphSession.smoothMaxPool (α := α) session
        (d := d) (C := channels) (inSpatial := spatial)
        (kernel := kernel) (stride := stride) (padding := padding) x beta

/-- Apply average pooling over an arbitrary number of spatial axes. -/
def avgPool {α : Type} [TorchLean.Storage α] (s : Session α) [Context α]
    {d channels : Nat} {spatial kernel stride padding : TorchLean.Tensor Nat [d]}
    (x : Runtime.Autograd.Torch.TensorRef α
      (Shape.ofList (channels :: spatial.to (List Nat)))) :
    IO (Runtime.Autograd.Torch.TensorRef α
      (Shape.ofList
        (channels ::
          (Spec.poolOutSpatialPad spatial kernel stride padding).to (List Nat)))) :=
  match s.state with
  | .eager session =>
      EagerSession.avgPool (α := α) session
        (d := d) (channels := channels) (spatial := spatial)
        (kernel := kernel) (stride := stride) (padding := padding) x
  | .typedGraph session =>
      Runtime.Autograd.Torch.Internal.TypedGraphSession.avgPool (α := α) session
        (d := d) (C := channels) (inSpatial := spatial)
        (kernel := kernel) (stride := stride) (padding := padding) x

end Session

end Model
end Autograd
end Runtime
